-- Seed draft docs for admin staging (NOT published)
-- Generated by scripts/generate-docs-staging-seed.mjs — do not hand-edit content blocks.
-- Requires: supabase/docs-staging-migration.sql

insert into public.doc_articles (
  slug, title, category, content, plan_visibility, order_index, status
) values
(
  'how-niskbuild-works',
  'How NiskBuild Works',
  'product',
  $md$# How NiskBuild Works

## What NiskBuild is

NiskBuild is an AI app builder: describe what you want in plain English, and NiskBuild generates real, working code — HTML, CSS, and JavaScript — that you can preview instantly, refine, and export. Unlike platforms that keep your app locked inside their system, NiskBuild gives you the actual source code, so what you build is genuinely yours.

## The build process

**1. You describe your app**
Type a prompt describing what you want — a business website, a booking page, a dashboard. The more specific you are, the more tailored the result, but even a short prompt is enough to get started.

**2. AI generates real code**
NiskBuild streams working code live as it's generated, so you can watch your app take shape. Generation runs on cloud AI by default, with automatic fallback across multiple providers if one is temporarily unavailable — so your build doesn't fail just because one provider is having issues.

**3. You get a live preview**
As code streams in, a live preview updates so you can see your app rendering in real time, not just read code.

**4. You iterate**
Add pages, request changes, or start over. Each successful save creates a version, so you can always go back to an earlier point if you want.

**5. You export or deploy**
When you're ready, export your code as a ZIP, deploy a shareable live preview link, or take it further with App Store/native app export options (see "Exporting Your App" below for exactly what each option includes).

## What "own your code forever" actually means

When you export a NiskBuild project, you get:
- A complete, cleaned HTML/CSS/JavaScript codebase
- A `niskbuild.config.json` file recording your project's prompt history and file structure
- A README explaining how to re-import the project back into NiskBuild if needed
- All pages of a multi-page project, not just the homepage

This is real, standalone code — it will run in any browser or web host, independent of NiskBuild, whether or not you keep your subscription.

*(Free/Sandbox tier exports include a visible watermark; paid tiers export a clean, unwatermarked version.)*

## Multi-page projects

NiskBuild supports multi-page apps — add a Contact page, an About page, or custom pages as your project grows. Once you save a project, all pages are stored together and restored exactly as you left them when you reopen the project. Version history also captures every page, not just the one you were last editing, so restoring an older version brings back your whole project as it was.

**One important note:** version history and multi-page saving apply after you've saved a project at least once. Before that first save, unsaved drafts may not fully persist if you leave and come back — save early if a project matters to you.

## Exporting your app

| Export type | What you get | Available on |
|---|---|---|
| Code ZIP | Full HTML/CSS/JS, config file, README, all pages | All tiers (watermarked on free; clean on paid) |
| PWA ZIP | Installable web-app package (manifest, service worker, offline support) | Paid tiers |
| Native starter ZIP | PWA package plus Capacitor configuration for wrapping as a mobile app | Agency tier and above |

*(Native starter ZIPs provide the configuration and instructions to build a native app yourself using standard developer tools — they are a starting point, not a finished App Store submission package.)*

## Version history

Every saved project keeps a version history you can browse, preview, and restore from. How many past versions are kept depends on your plan — higher tiers retain more history. Restoring an older version takes a snapshot of your current state first, so you never lose your latest work by going back.
$md$,
  '{all}'::text[],
  100,
  'draft'
),
(
  'plans-explained',
  'Plans Explained',
  'product',
  $md$# Plans Explained

## Sandbox — Free
**What's included:** 5 cloud AI credits (trial), 1 project, builder access after phone verification, watermarked ZIP export.
**Who it's for:** Anyone who wants to try NiskBuild before committing — no card required.

## Basic — $69/mo
**What's included:** 150 cloud AI credits, 5 projects, 2 sessions, clean (unwatermarked) ZIP export, PWA export, marketplace access, live preview deploy.
**Who it's for:** Solo freelancers and hobbyists who need real exports without a large volume of builds.

## Pro Worker — $129/mo
**What's included:** 600 cloud AI credits, 15 projects, 5 sessions, everything in Basic, plus BYOC (bring your own AI provider keys), local Ollama support, Google Places business data import, game templates, native mobile export pipeline.
**Who it's for:** Power users building regularly, who want more control over which AI provider generates their code.

## Agency Studio — $299/mo
**What's included:** 2,500 cloud AI credits, 25 projects, 10 sessions, everything in Pro Worker, plus native Capacitor export and competitor intelligence tools.
**Who it's for:** Studios and small teams shipping client work who need higher volume and native app export.
**Note:** Multi-seat team access is planned but not yet available — this tier is currently single-user, same as lower tiers.

## Scale Team — $799/mo
**What's included:** 10,000 cloud AI credits, unlimited projects, 20 sessions, everything in Agency Studio, plus scheduled social posting.
**Who it's for:** Growing teams with high build volume.
**Note:** Multi-seat team access is planned but not yet available.

## White-Label — $1,199/mo
**What's included:** 15,000 cloud AI credits, unlimited projects, unlimited sessions, everything in Scale Team, high-priority support tickets.
**Who it's for:** Resellers and agencies wanting to offer NiskBuild-powered building under their own brand.
**Note:** Self-serve custom domains and white-label rebranding are in active development — not yet available today. Multi-seat team access is also planned but not yet available.

## Team Enterprise — $1,999/mo
**What's included:** 25,000 cloud AI credits, unlimited projects and sessions, everything in White-Label, ticket-based support.
**Who it's for:** Mid-size companies needing high volume and dedicated support relationships.
**Note:** SSO, formal SLA contracts, and multi-seat team access are in active development — not yet available today.

## Sovereign — From $3,999/mo + setup fee
**What's included:** 50,000 cloud AI credits, unlimited projects and sessions, everything in Team Enterprise, custom support arrangements.
**Who it's for:** Large organizations with the highest volume needs.
**Note:** Dedicated infrastructure, SSO, custom SLA contracts, and multi-seat team access are in active development — not yet available today.
$md$,
  '{all}'::text[],
  101,
  'draft'
),
(
  'product-overview',
  'Product Overview',
  'product',
  $md$# NiskBuild — Product Overview (Marketing Summary)

**Describe your app. Get real code. Keep it forever.**

NiskBuild is the AI app builder that doesn't lock you in. Type what you want in plain English, watch AI build it in real time, and walk away with actual source code — not a rented app trapped on someone else's platform.

## The problem with most AI builders

Type a prompt into most AI app builders, and what you get back lives on their platform, under their terms. Stop paying, and it's gone. Your work, your ideas, your business — held hostage by a subscription.

## How NiskBuild is different

Every app you build on NiskBuild comes with clean, exportable code you can open, edit, host anywhere, or hand to a developer. If you ever leave NiskBuild, your apps don't leave with us.

**Build fast with AI. Leave whenever you want, with everything you made.**

## What you can do today

- **Describe, don't code.** A plain-English prompt is enough to generate a working app — a business site, a booking page, a dashboard, whatever you need.
- **Watch it happen live.** Real code streams in as it's generated, with a live preview updating in real time.
- **Grow it page by page.** Add pages as your project grows — everything saves together, with full version history so you can always go back.
- **Take it anywhere.** Export clean source code, deploy a live preview instantly, or package it for mobile.
- **Try before you commit.** Start free, no card required.

## Who it's for

- **Solo builders and freelancers** who need a real website or app fast, without hiring a developer for every change
- **Agencies and studios** shipping client work who want more volume and native export options
- **Growing teams and companies** that need higher build volume, and want the peace of mind that comes with owning what they build

## The bottom line

NiskBuild gives you speed without the trade-off. AI does the heavy lifting. You keep the result — forever.
$md$,
  '{all}'::text[],
  102,
  'draft'
),
(
  'niskbuild-for-companies',
  'NiskBuild for Companies',
  'product',
  $md$# NiskBuild for Companies
### White-Label · Team Enterprise · Sovereign

---

## Why companies need NiskBuild now

Every company has more app ideas than engineering hours to build them. Internal tools, client prototypes, landing pages, booking systems — the backlog grows faster than the team can clear it.

NiskBuild removes the bottleneck. Describe what you need, get real working code in minutes, and — critically — **own that code outright**. No dependency on a platform holding your work hostage. No "AI-generated but unusable without us" lock-in. Your team gets speed; your company keeps the output.

For companies operating at volume — running many projects, many prompts, many builds a month — the higher-tier plans exist specifically to remove the friction of hitting limits designed for individual users.

---

## What's real today

These enterprise tiers currently and reliably provide:

- **High-volume cloud AI credits** — from 15,000/month (White-Label) up to 50,000/month (Sovereign)
- **Unlimited projects and sessions** — no per-seat or per-project ceiling
- **Clean code export** — full HTML/CSS/JS, ready to deploy anywhere, no watermark
- **PWA and native mobile export** — installable web-app packages and a Capacitor-based mobile app starting point
- **Ticket-based support**, with priority handling on higher tiers
- **BYOC (Bring Your Own AI Provider)** — use your own LLM API keys if you have specific compliance or vendor requirements
- **GitHub sync** — push generated projects directly to your own repository
- **Stripe inject** — connect your own Stripe account to a generated app for real payment processing
- **Figma import** — bring existing design files into the builder as a starting point

---

## On the roadmap (not yet available)

We believe in being direct about where these tiers are heading versus where they are today. The following are in active development and **not yet functional**:

- Single sign-on (SSO / SAML / OIDC)
- Multi-seat team accounts with roles and invites
- Self-serve custom domain configuration
- White-label rebranding of the builder interface
- Formal SLA contracts
- Dedicated infrastructure isolation

If any of these are a hard requirement for your organization today, talk to us directly about timeline — we'd rather tell you honestly than have you discover a gap after signing up.

---

## What you'll need on your side

- **Individual accounts per team member** — since multi-seat organization accounts aren't built yet, each person who needs builder access needs their own NiskBuild login today
- **A GitHub account**, if you want generated projects synced to your own repository
- **A Stripe account**, if you want to connect real payment processing to a generated app
- **Your own LLM provider API key(s)**, if you want to use BYOC instead of NiskBuild's default cloud AI
- **A domain you control**, for when self-serve custom domains become available (not required today)

---

## The process, start to finish

1. **Sign up** and select your tier
2. **Describe your first project** in plain English — NiskBuild generates real working code with a live preview
3. **Iterate** — add pages, request changes, review version history as the project evolves
4. **Connect what you need** — sync to GitHub, inject your Stripe account, or bring your own AI provider keys
5. **Export or deploy** — clean ZIP, PWA package, native mobile starter, or a live shareable preview link
6. **Repeat across your team** — each team member builds independently on their own account today; true shared team workspaces are coming
$md$,
  '{all}'::text[],
  103,
  'draft'
)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  content = excluded.content,
  plan_visibility = excluded.plan_visibility,
  order_index = excluded.order_index,
  status = excluded.status,
  updated_at = now();
