-- Seed draft docs for admin staging (NOT published)
-- Generated by scripts/generate-docs-staging-seed.mjs — do not hand-edit content blocks.
-- Requires: supabase/docs-staging-migration.sql

insert into public.doc_articles (
  slug, title, category, content, plan_visibility, order_index, status
) values
(
  'how-niskbuild-works',
  'How NiskBuild Works',
  'product',
  $md$# How NiskBuild Works

## What NiskBuild is

NiskBuild is an AI app builder: describe what you want in plain English, and NiskBuild generates real, working code — HTML, CSS, and JavaScript — that you can preview instantly, refine, and export. Unlike platforms that keep your app locked inside their system, NiskBuild gives you the actual source code, so what you build is genuinely yours.

You don't need to know how to code. You don't need a technical team. You describe what you need the way you'd describe it to a person, and NiskBuild builds it.

## The build process

**1. You describe your app**
Type a prompt describing what you want — a business website, a booking page, a dashboard for tracking deliveries, an internal tool for your staff. The more specific you are, the more tailored the result, but even a short prompt is enough to get started.

**2. AI generates real code**
NiskBuild streams working code live as it's generated, so you can watch your app take shape. Generation runs on cloud AI by default, with automatic backup across multiple AI providers if one is temporarily unavailable — so your build doesn't fail just because one provider is having issues.

**3. You get a live preview**
As code streams in, a live preview updates so you can see your app rendering in real time, not just read code.

**4. You iterate**
Add pages, request changes, or start over. Each successful save creates a version, so you can always go back to an earlier point if you want.

**5. You export or deploy**
When you're ready, export your code as a downloadable package, publish a shareable live link, or take it further with app store export options.

## What "own your code forever" actually means

When you export a NiskBuild project, you get a complete, working codebase — not a locked file you can only open inside NiskBuild. This includes:
- All your app's actual code, ready to run in any web browser or hosting service
- A record of your project's history and structure
- Instructions for bringing the project back into NiskBuild later if needed
- Every page of a multi-page project, not just the homepage

This means: if you ever stop paying for NiskBuild, or decide to move to a different provider, you keep everything you built. It doesn't disappear.

*(Free trial exports include a small watermark; paid plans export a clean version with no watermark.)*

## Multi-page projects

NiskBuild supports apps with multiple pages — add a Contact page, an About page, or custom pages as your project grows. Once you save a project, all pages are stored together and restored exactly as you left them. Version history also captures every page, not just the one you were last editing.

## Understanding a few technical terms

We try to avoid jargon, but a few terms come up when discussing plans and setup. Here's what they actually mean:

**SSL (the padlock icon in your browser)** — this is what encrypts the connection between your visitors and your website, protecting information they enter. Every domain on NiskBuild, including your own custom domain if you use one, gets this automatically — you don't need to set anything up yourself.

**SSO (Single Sign-On)** — a way for your employees to log into NiskBuild using the same company account they already use for email or other work tools (like Microsoft or Google Workspace), instead of a separate password. This matters mainly for larger companies with IT departments managing employee access centrally.

**SLA (Service Level Agreement)** — a formal, written commitment about how reliable and responsive our support is — for example, a guarantee of how quickly we respond to a support request. This is typically something larger companies request as part of a contract, and we work these out individually for that reason.

**API / Integration** — a way for two pieces of software to talk to each other automatically. If your company uses a system like Stripe for payments, NiskBuild can connect a generated app directly to it.

## Exporting your app

| Export type | What you get | Available on |
|---|---|---|
| Code package | Full source code, all pages, ready to host anywhere | All plans (watermarked on free trial; clean on paid plans) |
| Installable web app | A version of your app that can be installed like an app, works offline | Paid plans |
| Mobile app starter | The starting files needed to turn your app into an iOS/Android app | Higher-tier plans |

## Version history

Every saved project keeps a history you can browse and restore from at any time. How far back your history goes depends on your plan — higher tiers keep more history. Restoring an older version never loses your latest work — it's saved first, automatically.
$md$,
  '{all}'::text[],
  100,
  'draft'
),
(
  'plans-explained',
  'Plans Explained',
  'product',
  $md$# Plans Explained

Every plan includes the full AI builder. As you move up, you get more monthly usage, more advanced export options, and — starting at Agency Studio — the ability to bring your whole team onto one account.

## Sandbox — Free
**What's included:** A limited free trial (5 AI generations), 1 project, builder access after a quick phone verification, watermarked export.
**Who it's for:** Anyone who wants to try NiskBuild before paying anything. No card required.

## Basic — $69/mo
**What's included:** 150 AI generations/month, 5 projects, clean (no watermark) code export, installable web app export, access to the app marketplace, instant shareable preview links.
**Who it's for:** Solo freelancers and small businesses that need a real, working website or tool without a large monthly volume of builds.

## Pro Worker — $129/mo
**What's included:** 600 AI generations/month, 15 projects, everything in Basic, plus the option to use your own AI provider account if you have one, offline/local building, importing real business details automatically (like your Google Business listing), and a mobile app export starting point.
**Who it's for:** People building regularly — freelancers with steady client work, or a small business building multiple internal tools.

## Agency Studio — $299/mo
**What's included:** 2,500 AI generations/month, 25 projects, everything in Pro Worker, plus mobile app export tools and competitor research tools. **Team accounts start here** — up to 3 people (including you) can share one account and one subscription.
**Who it's for:** Small agencies and studios building for multiple clients, or a small internal team that wants to build together.

## Scale Team — $799/mo
**What's included:** 10,000 AI generations/month, unlimited projects, everything in Agency Studio, plus scheduled social media posting. **Up to 10 team members.**
**Who it's for:** Growing teams and businesses with regular, high-volume building needs.

## White-Label — $1,199/mo
**What's included:** 15,000 AI generations/month, unlimited projects, everything in Scale Team, plus the ability to connect your own domain name (yourcompany.com instead of a NiskBuild address), and remove all NiskBuild branding from what you publish — your customers see your company's name, not ours. **Up to 15 team members.**
**Who it's for:** Agencies, resellers, and larger companies who want to offer building services under their own brand, or simply want a fully private, professional presence with no third-party branding.

## Team Enterprise — $1,999/mo
**What's included:** 25,000 AI generations/month, unlimited projects, everything in White-Label, plus company login (SSO) so your staff can sign in with their existing work accounts, and priority support. **Up to 25 team members.**
**Who it's for:** Mid-size companies with an IT department, who need centralized control over who has access and a higher level of support.

## Sovereign — From $3,999/mo + setup fee
**What's included:** 50,000 AI generations/month, unlimited projects, everything in Team Enterprise, plus custom support arrangements discussed individually. **Up to 50 team members.**
**Who it's for:** Large organizations with the highest volume needs and the most specific requirements — we work with you directly to shape this tier around what your company actually needs.

---

## A note on formal support commitments and dedicated infrastructure

For companies that need a formally guaranteed response time (a Service Level Agreement, or "SLA") or their own fully separate, isolated technical environment, we're actively building toward offering this for Team Enterprise and Sovereign customers. If this is something your company needs, get in touch — we'll work through exactly what you need and what we can commit to.
$md$,
  '{all}'::text[],
  101,
  'draft'
),
(
  'product-overview',
  'Product Overview',
  'product',
  $md$# NiskBuild — Product Overview (Marketing Summary)

**Describe your app. Get real code. Keep it forever.**

NiskBuild is the AI app builder that doesn't lock you in. Type what you want in plain English, watch AI build it in real time, and walk away with actual source code — not a rented app trapped on someone else's platform.

## The problem with most AI builders

Type a prompt into most AI app builders, and what you get back lives on their platform, under their terms. Stop paying, and it's gone. Your work, your ideas, your business — held hostage by a subscription.

## How NiskBuild is different

Every app you build on NiskBuild comes with clean, exportable code you can open, edit, host anywhere, or hand to a developer. If you ever leave NiskBuild, your apps don't leave with us.

**Build fast with AI. Leave whenever you want, with everything you made.**

## What you can do today

- **Describe, don't code.** A plain-English prompt is enough to generate a working app — a business site, a booking page, a dashboard, whatever you need.
- **Watch it happen live.** Real code streams in as it's generated, with a live preview updating in real time.
- **Grow it page by page.** Add pages as your project grows — everything saves together, with full version history so you can always go back.
- **Take it anywhere.** Export clean source code, deploy a live preview instantly, or package it for mobile.
- **Try before you commit.** Start free, no card required.

## Who it's for

- **Solo builders and freelancers** who need a real website or app fast, without hiring a developer for every change
- **Agencies and studios** shipping client work who want more volume and native export options
- **Growing teams and companies** that need higher build volume, and want the peace of mind that comes with owning what they build

## The bottom line

NiskBuild gives you speed without the trade-off. AI does the heavy lifting. You keep the result — forever.
$md$,
  '{all}'::text[],
  102,
  'draft'
),
(
  'niskbuild-for-companies',
  'NiskBuild for Companies',
  'product',
  $md$# NiskBuild for Companies
### For teams and organizations of any kind — technical or not

---

## The problem we solve

Every company — whether you're a software startup or a food distribution business running on spreadsheets and phone calls — has more things you need built than you have people to build them. A booking page. An internal tool to track deliveries. A dashboard your managers actually want to use. A branded portal for your resellers.

Traditionally, that means hiring developers, waiting weeks or months, and paying a lot of money — for something that might need to change again in three months anyway.

NiskBuild removes that bottleneck. Anyone on your team describes what they need, in plain English, and gets a real, working piece of software back in minutes. And critically: **you own what gets built.** It's not trapped inside our platform — it's real code you can take anywhere, forever.

## What your team actually gets

- **No coding required.** If someone on your team can describe what they want clearly, they can build it.
- **Real ownership.** Every app comes with exportable code — not a demo, not a locked preview. You can hand it to a developer, host it yourselves, or keep building on NiskBuild. Your choice, always.
- **Your whole team, one place.** Starting at our Agency Studio plan, multiple people from your company share one account, working on shared projects together.
- **Your brand, not ours.** On our White-Label plan and above, you can connect your own website address and remove all NiskBuild branding — your customers and staff never see our name.
- **Fits into how you already work.** Connect your own payment processor, sync generated projects to your own code storage, or use your own AI provider account if your company already has one.

## Plain-English glossary (for non-technical decision-makers)

You don't need to understand these to use NiskBuild — but if your IT team or a technical advisor asks about them, here's what they mean:

- **SSL** — the security that protects any information entered on your website (already included automatically, no setup needed on your part)
- **SSO (Single Sign-On)** — lets your employees log in with their existing work email/account instead of a separate password (available on Team Enterprise and above)
- **Custom domain** — using your own website address (like www.yourcompany.com) instead of a NiskBuild one (available on White-Label and above)
- **API / Integration** — a way to automatically connect NiskBuild to other software your company already uses
- **SLA (Service Level Agreement)** — a formal written promise about response times and reliability, typically arranged individually for larger contracts

## What's available today, by plan level

| | White-Label | Team Enterprise | Sovereign |
|---|---|---|---|
| Team members included | Up to 15 | Up to 25 | Up to 50 |
| Your own domain name | ✓ | ✓ | ✓ |
| Remove our branding entirely | ✓ | ✓ | ✓ |
| Staff login with company account (SSO) | — | ✓ | ✓ |
| Priority support | — | ✓ | ✓ |
| Formal support guarantees & dedicated setup | In development — talk to us | In development — talk to us | In development — talk to us |

## What you'll need on your side

- **One account per team member.** Right now, each person needs their own login — we don't yet support one shared login for the whole team logging in as themselves (this is standard for now, similar to most business software).
- **A domain name you own**, if you want your own web address instead of a NiskBuild one.
- **Your company's identity provider details** (like Microsoft 365 or Google Workspace), if you want staff logging in with their existing work accounts.
- **A payment processor account**, if you want a generated app to accept real payments directly.

## The process, start to finish

1. **Sign up and choose your plan** based on team size and needs.
2. **Invite your team.** Send invitations by email; each person accepts and joins your shared workspace.
3. **Start building.** Anyone on the team describes what they need — no technical skill required — and gets real, working software back.
4. **Make it yours.** Connect your own domain name, remove our branding, and connect any other tools your company already uses.
5. **Keep everything.** Export any project's full code at any time — it's yours, whether or not you continue with NiskBuild.

---

Have questions, or need something not listed here? Contact us directly — larger commitments like guaranteed response times or fully dedicated technical infrastructure are worked out individually, because every company's needs are different.
$md$,
  '{all}'::text[],
  103,
  'draft'
)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  content = excluded.content,
  plan_visibility = excluded.plan_visibility,
  order_index = excluded.order_index,
  status = excluded.status,
  updated_at = now();
