/**
 * Blessed Islamic Days — canonical dataset
 * hijri_month (1-12), hijri_day (null = full month)
 * Days are checked against the current Hijri date from AlAdhan API.
 */
export const BLESSED_DAYS = [
  {
    id: 'laylatul_qadr_21',
    name: "Laylatul Qadr (21st)",
    arabic: "لَيْلَةُ الْقَدْرِ",
    emoji: '✨',
    hijri_month: 9, hijri_day: 21,
    days_before_reminder: [7, 3, 1],
    priority: 'urgent',
    description: "The Night of Power — better than a thousand months (Quran 97:3). One of the odd nights in the last 10 of Ramadan.",
    sunnah_actions: [
      "Pray Tahajjud and increase nawafil prayers",
      "Recite: 'Allahumma innaka 'afuwwun tuhibbul 'afwa fa'fu 'anni' abundantly",
      "Make du'a for yourself, family, and the Ummah",
      "Read and reflect on Surah Al-Qadr (97)",
      "Give Sadaqah — even a small amount on this night",
      "Perform I'tikaf if possible",
    ],
    color: 'indigo',
  },
  {
    id: 'laylatul_qadr_23',
    name: "Laylatul Qadr (23rd)",
    arabic: "لَيْلَةُ الْقَدْرِ",
    emoji: '✨',
    hijri_month: 9, hijri_day: 23,
    days_before_reminder: [1],
    priority: 'urgent',
    description: "Potential Night of Power — seek it on the odd nights of the last 10 nights of Ramadan.",
    sunnah_actions: [
      "Stay awake for night worship",
      "Recite the Laylatul Qadr du'a abundantly",
      "Give charity before Fajr",
      "Recite Surah Al-Ikhlas 1000 times for immense reward",
    ],
    color: 'indigo',
  },
  {
    id: 'laylatul_qadr_25',
    name: "Laylatul Qadr (25th)",
    arabic: "لَيْلَةُ الْقَدْرِ",
    emoji: '✨',
    hijri_month: 9, hijri_day: 25,
    days_before_reminder: [1],
    priority: 'urgent',
    description: "Potential Night of Power — 25th night of Ramadan.",
    sunnah_actions: [
      "Increase dhikr and istighfar throughout the night",
      "Perform Witr prayer with du'a qunut",
      "Read Quran with reflection",
    ],
    color: 'indigo',
  },
  {
    id: 'laylatul_qadr_27',
    name: "Laylatul Qadr (27th)",
    arabic: "لَيْلَةُ الْقَدْرِ",
    emoji: '✨',
    hijri_month: 9, hijri_day: 27,
    days_before_reminder: [3, 1],
    priority: 'urgent',
    description: "The most commonly narrated night for Laylatul Qadr — 27th of Ramadan.",
    sunnah_actions: [
      "Pray all five prayers in congregation",
      "Recite the Laylatul Qadr du'a 100+ times",
      "Fast and break fast with du'a",
      "Give Zakat and Sadaqah",
      "Recite Surah Al-Dukhan",
      "Perform ghusl and wear your best clothes for night prayer",
    ],
    color: 'indigo',
  },
  {
    id: 'laylatul_qadr_29',
    name: "Laylatul Qadr (29th)",
    arabic: "لَيْلَةُ الْقَدْرِ",
    emoji: '✨',
    hijri_month: 9, hijri_day: 29,
    days_before_reminder: [1],
    priority: 'urgent',
    description: "Final odd night of Ramadan — last chance for Laylatul Qadr.",
    sunnah_actions: [
      "Intensify worship before Ramadan ends",
      "Make tawbah (repentance) sincerely",
      "Recite Laylatul Qadr du'a throughout the night",
    ],
    color: 'indigo',
  },
  {
    id: 'day_of_arafah',
    name: "Day of Arafah",
    arabic: "يَوْمُ عَرَفَةَ",
    emoji: '🕋',
    hijri_month: 12, hijri_day: 9,
    days_before_reminder: [7, 3, 1],
    priority: 'urgent',
    description: "The best day of the year. Fasting on this day expiates sins of two years (Muslim). The pilgrims stand at Arafah.",
    sunnah_actions: [
      "Fast — it expiates sins of the past and coming year",
      "Recite 'La ilaha illallah wahdahu la sharika lah…' abundantly",
      "Make du'a after Asr until Maghrib",
      "Read Surah Al-Kahf (18)",
      "Give charity generously",
      "Recite Takbir al-Tashreeq: Allahu Akbar, Allahu Akbar, la ilaha illallah...",
    ],
    color: 'amber',
  },
  {
    id: 'eid_al_adha',
    name: "Eid al-Adha",
    arabic: "عِيدُ الْأَضْحَى",
    emoji: '🐑',
    hijri_month: 12, hijri_day: 10,
    days_before_reminder: [7, 3, 1],
    priority: 'high',
    description: "Festival of Sacrifice — commemorating Prophet Ibrahim's willingness to sacrifice his son for Allah.",
    sunnah_actions: [
      "Perform Eid prayer in congregation",
      "Offer Udhiyah (Qurbani) if you are able",
      "Recite Takbir on the way to Eid prayer",
      "Eat from the Qurbani meat and share with neighbours",
      "Wear your best clothes and apply perfume",
      "Take different routes to and from the prayer",
    ],
    color: 'orange',
  },
  {
    id: 'ashura',
    name: "Day of Ashura",
    arabic: "يَوْمُ عَاشُورَاء",
    emoji: '🌊',
    hijri_month: 1, hijri_day: 10,
    days_before_reminder: [10, 3, 1],
    priority: 'high',
    description: "Allah saved Prophet Musa (AS) on this day. Fasting expiates sins of the previous year (Muslim).",
    sunnah_actions: [
      "Fast on the 10th of Muharram",
      "Also fast the 9th (Tasu'a) to differ from the Jews",
      "Increase in voluntary worship",
      "Give Sadaqah to family and the needy",
      "Recite: 'HasbunAllahu wa ni'mal wakeel' 70 times",
    ],
    color: 'blue',
  },
  {
    id: 'tasu_a',
    name: "Day of Tasu'a",
    arabic: "يَوْمُ تَاسُوعَاء",
    emoji: '🌊',
    hijri_month: 1, hijri_day: 9,
    days_before_reminder: [1],
    priority: 'medium',
    description: "The 9th of Muharram — it is Sunnah to fast this day alongside Ashura.",
    sunnah_actions: [
      "Fast on this day alongside Ashura",
      "Make intention before Fajr",
      "Increase in du'a and dhikr",
    ],
    color: 'blue',
  },
  {
    id: 'mawlid',
    name: "Mawlid al-Nabi ﷺ",
    arabic: "مَوْلِدُ النَّبِيِّ",
    emoji: '🌹',
    hijri_month: 3, hijri_day: 12,
    days_before_reminder: [7, 1],
    priority: 'medium',
    description: "Birthday of the Prophet Muhammad ﷺ — 12th of Rabi' al-Awwal.",
    sunnah_actions: [
      "Send abundant salawat upon the Prophet ﷺ",
      "Read his Seerah (biography)",
      "Teach children about the life of the Prophet ﷺ",
      "Give charity in gratitude for his message",
    ],
    color: 'green',
  },
  {
    id: 'isra_miraj',
    name: "Isra' wal Mi'raj",
    arabic: "الإسراء والمعراج",
    emoji: '🌟',
    hijri_month: 7, hijri_day: 27,
    days_before_reminder: [7, 1],
    priority: 'medium',
    description: "The Night Journey and Ascension of the Prophet ﷺ — when the five daily prayers were prescribed.",
    sunnah_actions: [
      "Increase in Salah and nawafil prayers",
      "Reflect on the miracle of the Night Journey",
      "Read about the significance of the five prayers",
      "Pray 2 rak'ah in gratitude for the blessing of Salah",
    ],
    color: 'purple',
  },
  {
    id: 'laylatul_bara',
    name: "Laylatul Bara'ah",
    arabic: "لَيْلَةُ الْبَرَاءَةِ",
    emoji: '🌕',
    hijri_month: 8, hijri_day: 15,
    days_before_reminder: [3, 1],
    priority: 'medium',
    description: "Night of Forgiveness — 15th of Sha'ban. Some scholars recommend extra worship.",
    sunnah_actions: [
      "Seek forgiveness sincerely",
      "Pray nafl prayers during the night",
      "Fast on the 13th, 14th and 15th of Sha'ban (ayyam al-bid)",
      "Recite istighfar 100 times",
    ],
    color: 'pink',
  },
  {
    id: 'first_dhul_hijjah',
    name: "First 10 Days of Dhul Hijjah",
    arabic: "عَشْرُ ذِي الْحِجَّةِ",
    emoji: '🌙',
    hijri_month: 12, hijri_day: 1,
    days_before_reminder: [7, 1],
    priority: 'high',
    description: "The best days of the entire year for good deeds (Bukhari). Increase worship, fasting and dhikr.",
    sunnah_actions: [
      "Fast as many of the first 9 days as possible",
      "Recite Takbir, Tahmid, Tahlil abundantly",
      "Give abundant Sadaqah",
      "Perform Udhiyah (do not cut nails or hair if intending Qurbani)",
      "Read Quran daily with reflection",
      "Pray all 5 prayers on time in congregation",
    ],
    color: 'amber',
  },
  {
    id: 'ramadan_start',
    name: "Ramadan Begins",
    arabic: "رَمَضَانُ",
    emoji: '🌙',
    hijri_month: 9, hijri_day: 1,
    days_before_reminder: [14, 7, 1],
    priority: 'urgent',
    description: "The blessed month of fasting, Quran and increased worship.",
    sunnah_actions: [
      "Make sincere intention to fast the whole month",
      "Set a Quran reading goal for the month",
      "Increase charity — Prophet ﷺ was most generous in Ramadan",
      "Pray Tarawih every night",
      "Plan I'tikaf for the last 10 nights",
    ],
    color: 'purple',
  },
  {
    id: 'eid_al_fitr',
    name: "Eid al-Fitr",
    arabic: "عِيدُ الْفِطْرِ",
    emoji: '🎉',
    hijri_month: 10, hijri_day: 1,
    days_before_reminder: [7, 1],
    priority: 'high',
    description: "Festival of Breaking the Fast — a day of joy and gratitude after Ramadan.",
    sunnah_actions: [
      "Pay Zakat al-Fitr before Eid prayer",
      "Eat something sweet (dates) before prayer",
      "Perform Eid prayer in congregation",
      "Greet fellow Muslims with 'Eid Mubarak'",
      "Visit family and strengthen ties",
      "Give gifts to children",
    ],
    color: 'green',
  },
];

export const COLOR_MAP = {
  indigo:  { bg: 'bg-indigo-50 dark:bg-indigo-950/20',  border: 'border-indigo-200 dark:border-indigo-800/40',  text: 'text-indigo-700 dark:text-indigo-300',  badge: 'bg-indigo-100 dark:bg-indigo-900/40 text-indigo-700 dark:text-indigo-300' },
  amber:   { bg: 'bg-amber-50 dark:bg-amber-950/20',    border: 'border-amber-200 dark:border-amber-800/40',    text: 'text-amber-700 dark:text-amber-300',    badge: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300' },
  orange:  { bg: 'bg-orange-50 dark:bg-orange-950/20',  border: 'border-orange-200 dark:border-orange-800/40',  text: 'text-orange-700 dark:text-orange-300',  badge: 'bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-300' },
  blue:    { bg: 'bg-blue-50 dark:bg-blue-950/20',      border: 'border-blue-200 dark:border-blue-800/40',      text: 'text-blue-700 dark:text-blue-300',      badge: 'bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300' },
  green:   { bg: 'bg-emerald-50 dark:bg-emerald-950/20',border: 'border-emerald-200 dark:border-emerald-800/40',text: 'text-emerald-700 dark:text-emerald-300', badge: 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300' },
  purple:  { bg: 'bg-purple-50 dark:bg-purple-950/20',  border: 'border-purple-200 dark:border-purple-800/40',  text: 'text-purple-700 dark:text-purple-300',  badge: 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300' },
  pink:    { bg: 'bg-pink-50 dark:bg-pink-950/20',      border: 'border-pink-200 dark:border-pink-800/40',      text: 'text-pink-700 dark:text-pink-300',      badge: 'bg-pink-100 dark:bg-pink-900/40 text-pink-700 dark:text-pink-300' },
};