/** Shift AI Tailwind class bundles — requires `.shift-ai-app` ancestor (shift-ai.css). */

export const SA = {
  content: 'mx-auto max-w-5xl p-6 md:p-10',
  contentNarrow: 'mx-auto max-w-3xl p-6 md:p-10',
  heading: 'text-2xl font-bold sa-text md:text-3xl',
  headingMd: 'text-2xl font-bold sa-text',
  subheading: 'text-lg font-semibold sa-text',
  sectionLabel: 'mb-3 text-sm font-semibold uppercase tracking-wide sa-muted',
  muted: 'sa-muted',
  text: 'sa-text',
  card: 'sa-card rounded-2xl',
  cardPadded: 'sa-card rounded-2xl p-5',
  cardHover: 'sa-card sa-card-hover rounded-2xl transition-all',
  tip: 'sa-tip p-4 text-sm',
  badge: 'sa-badge px-2 py-0.5 text-xs font-medium',
  badgeSm: 'sa-badge px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide',
  input: 'sa-input w-full px-3 py-2.5 text-sm',
  select: 'sa-select w-full px-3 py-2 text-sm',
  textarea: 'sa-textarea w-full px-4 py-3 text-sm leading-relaxed',
  btnPrimary: 'sa-btn-primary inline-flex items-center justify-center gap-2 px-4 py-2 text-sm disabled:opacity-60',
  btnPrimaryIcon: 'sa-btn-primary inline-flex items-center justify-center px-3 py-2 disabled:opacity-60',
  btnSecondary: 'sa-btn-secondary px-4 py-2 text-sm disabled:opacity-60',
  tab: 'sa-tab flex flex-shrink-0 items-center gap-1.5 whitespace-nowrap px-3 py-2.5 text-xs font-medium transition-colors',
  tabActive: 'sa-tab-active flex flex-shrink-0 items-center gap-1.5 whitespace-nowrap px-3 py-2.5 text-xs font-medium transition-colors',
  userBubble: 'sa-user-bubble max-w-[78%] whitespace-pre-wrap rounded-2xl rounded-br-sm px-4 py-3 text-sm leading-relaxed',
  assistBubble:
    'sa-assist-bubble max-w-[78%] whitespace-pre-wrap rounded-2xl rounded-bl-sm px-4 py-3 text-sm leading-relaxed',
  avatar: 'sa-avatar flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full',
  avatarLg: 'sa-avatar flex h-12 w-12 items-center justify-center rounded-2xl',
  chatPanel: 'flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl sa-card',
  iconHeader: 'sa-avatar flex h-11 w-11 items-center justify-center rounded-2xl bg-[var(--sa-navy-800)] text-white',
  authPage: 'sa-auth-page px-6 py-16',
  authKicker: 'sa-auth-kicker text-sm',
  authCard: 'sa-auth-card p-5',
  authChoice: 'sa-auth-choice w-full p-5 text-left',
  link: 'sa-link text-sm',
  error: 'sa-error rounded-lg px-4 py-3 text-sm',
  success: 'sa-success rounded-lg px-4 py-3 text-sm',
} as const;
