import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

/**
 * Share event details to Google Drive as a document
 */
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const {
      event_id,
      event_data,
      file_name,
      folder_path
    } = await req.json();

    if (!event_id || !event_data || !file_name) {
      return Response.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Get Google Drive access token
    const accessToken = await base44.asServiceRole.connectors.getAccessToken('googledrive');

    // Create formatted document content
    const content = formatEventDocument(event_data);

    // Create the file in Google Drive
    const fileName = `${file_name}.txt`;
    const mimeType = 'text/plain';

    const metadata = {
      name: fileName,
      mimeType: mimeType
    };

    // Check if folder_path exists, if not create it
    let parentFolderId = 'root';
    if (folder_path) {
      parentFolderId = await findOrCreateFolder(accessToken, folder_path);
    }

    metadata.parents = [parentFolderId];

    // Create the file
    const form = new FormData();
    form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
    form.append('file', new Blob([content], { type: mimeType }));

    const response = await fetch(
      'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart',
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`
        },
        body: form
      }
    );

    if (!response.ok) {
      const error = await response.json();
      return Response.json(
        { 
          success: false,
          error: error.error?.message || 'Failed to upload to Google Drive'
        },
        { status: response.status }
      );
    }

    const fileData = await response.json();

    // Log the action
    try {
      await base44.asServiceRole.entities.IntegrationLog?.create?.({
        user_email: user.email,
        action: 'share_event_to_google_drive',
        integration_type: 'googledrive',
        event_id,
        metadata: {
          file_id: fileData.id,
          file_name: fileName
        },
        created_at: new Date().toISOString()
      }).catch(() => {});
    } catch (err) {
      console.error('Failed to log integration action:', err);
    }

    return Response.json({
      success: true,
      file_id: fileData.id,
      file_name: fileData.name,
      web_link: fileData.webViewLink
    });
  } catch (error) {
    console.error('Error sharing to Google Drive:', error);
    return Response.json(
      { error: error.message },
      { status: 500 }
    );
  }
});

/**
 * Format event data as a readable document
 */
function formatEventDocument(event) {
  const lines = [];
  
  lines.push('='.repeat(50));
  lines.push(`EVENT: ${event.title}`);
  lines.push('='.repeat(50));
  lines.push('');

  if (event.description) {
    lines.push('DESCRIPTION:');
    lines.push(event.description);
    lines.push('');
  }

  if (event.start_date) {
    lines.push(`DATE: ${event.start_date}`);
    if (event.end_date) {
      lines.push(`END: ${event.end_date}`);
    }
    lines.push('');
  }

  if (event.location) {
    lines.push(`LOCATION: ${event.location}`);
    lines.push('');
  }

  if (event.attendees && event.attendees.length > 0) {
    lines.push('ATTENDEES:');
    event.attendees.forEach(attendee => {
      lines.push(`  • ${attendee}`);
    });
    lines.push('');
  }

  lines.push('Generated by MyAssistant');
  lines.push(`Created: ${new Date().toISOString()}`);

  return lines.join('\n');
}

/**
 * Find or create a folder in Google Drive
 */
async function findOrCreateFolder(accessToken, folderPath) {
  const parts = folderPath.split('/').filter(p => p.length > 0);
  let parentId = 'root';

  for (const folderName of parts) {
    // Search for folder
    const searchResponse = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${folderName}' and mimeType='application/vnd.google-apps.folder' and '${parentId}' in parents and trashed=false&spaces=drive&fields=files(id)`,
      {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      }
    );

    const searchData = await searchResponse.json();

    if (searchData.files && searchData.files.length > 0) {
      parentId = searchData.files[0].id;
    } else {
      // Create folder
      const createResponse = await fetch(
        'https://www.googleapis.com/drive/v3/files',
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            name: folderName,
            mimeType: 'application/vnd.google-apps.folder',
            parents: [parentId]
          })
        }
      );

      const createData = await createResponse.json();
      parentId = createData.id;
    }
  }

  return parentId;
}