/** Ember Habits fixture from Full App generation smoke — for preview integration evidence. */
import type { ProjectFile } from '@/lib/project-files';
import { iconForProjectPath } from '@/lib/full-app-bundle';

const RAW: Record<string, string> = {
  "index.html": "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Ember Habits</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.jsx\"></script>\n  </body>\n</html>",
  "package.json": "{\n  \"name\": \"ember-habits\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"dev\": \"vite\",\n    \"build\": \"vite build\",\n    \"preview\": \"vite preview\"\n  },\n  \"dependencies\": {\n    \"react\": \"^18.2.0\",\n    \"react-dom\": \"^18.2.0\",\n    \"react-router-dom\": \"^6.14.2\"\n  },\n  \"devDependencies\": {\n    \"vite\": \"^5.0.0\",\n    \"@vitejs/plugin-react\": \"^4.2.0\"\n  }\n}",
  "src/App.jsx": "import React from 'react';\nimport { Outlet } from 'react-router-dom';\nimport Nav from './components/Nav.jsx';\nimport AppRoutes from './routes.jsx';\n\nexport default function App() {\n  return (\n    <div className=\"app\">\n      <Nav />\n      <main className=\"content\">\n        <AppRoutes />\n        <Outlet />\n      </main>\n    </div>\n  );\n}",
  "src/components/HabitItem.jsx": "import React from 'react';\nimport { useHabits } from '../context/HabitContext.jsx';\n\nexport default function HabitItem({ habit }) {\n  const { toggleHabit } = useHabits();\n\n  return (\n    <li className={`habit-item ${habit.completed ? 'completed' : ''}`}>\n      <span>{habit.name}</span>\n      <button onClick={() => toggleHabit(habit.id)}>\n        {habit.completed ? 'Undo' : 'Done'}\n      </button>\n    </li>\n  );\n}",
  "src/components/Nav.jsx": "import React from 'react';\nimport { NavLink } from 'react-router-dom';\n\nexport default function Nav() {\n  return (\n    <nav>\n      <NavLink to=\"/\" end className={({ isActive }) => (isActive ? 'active' : '')}>\n        Home\n      </NavLink>\n      <NavLink to=\"/habits\" className={({ isActive }) => (isActive ? 'active' : '')}>\n        Habits\n      </NavLink>\n    </nav>\n  );\n}",
  "src/context/HabitContext.jsx": "import React, { createContext, useContext, useEffect, useState } from 'react';\n\nconst HabitContext = createContext();\n\nexport function HabitProvider({ children }) {\n  const [habits, setHabits] = useState(() => {\n    const stored = localStorage.getItem('habits');\n    return stored ? JSON.parse(stored) : [];\n  });\n\n  useEffect(() => {\n    localStorage.setItem('habits', JSON.stringify(habits));\n  }, [habits]);\n\n  const addHabit = (name) => {\n    setHabits((prev) => [\n      ...prev,\n      { id: Date.now(), name, completed: false, lastToggled: null },\n    ]);\n  };\n\n  const toggleHabit = (id) => {\n    setHabits((prev) =>\n      prev.map((h) =>\n        h.id === id\n          ? {\n              ...h,\n              completed: !h.completed,\n              lastToggled: new Date().toISOString(),\n            }\n          : h\n      )\n    );\n  };\n\n  const value = { habits, addHabit, toggleHabit };\n  return (\n    <HabitContext.Provider value={value}>{children}</HabitContext.Provider>\n  );\n}\n\nexport function useHabits() {\n  return useContext(HabitContext);\n}",
  "src/main.jsx": "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { BrowserRouter } from 'react-router-dom';\nimport { HabitProvider } from './context/HabitContext.jsx';\nimport App from './App.jsx';\nimport './styles.css';\n\ncreateRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <HabitProvider>\n      <BrowserRouter>\n        <App />\n      </BrowserRouter>\n    </HabitProvider>\n  </React.StrictMode>\n);",
  "src/pages/Habits.jsx": "import React, { useState } from 'react';\nimport { useHabits } from '../context/HabitContext.jsx';\nimport HabitItem from '../components/HabitItem.jsx';\n\nexport default function Habits() {\n  const { habits, addHabit } = useHabits();\n  const [name, setName] = useState('');\n\n  const handleAdd = (e) => {\n    e.preventDefault();\n    const trimmed = name.trim();\n    if (trimmed) {\n      addHabit(trimmed);\n      setName('');\n    }\n  };\n\n  return (\n    <section>\n      <h1>Your Habits</h1>\n      <form onSubmit={handleAdd} style={{ marginBottom: '1rem' }}>\n        <input\n          type=\"text\"\n          placeholder=\"New habit name\"\n          value={name}\n          onChange={(e) => setName(e.target.value)}\n          required\n        />\n        <button type=\"submit\">Add</button>\n      </form>\n\n      {habits.length === 0 ? (\n        <p>No habits yet. Add one above!</p>\n      ) : (\n        <ul className=\"habit-list\">\n          {habits.map((h) => (\n            <HabitItem key={h.id} habit={h} />\n          ))}\n        </ul>\n      )}\n    </section>\n  );\n}",
  "src/pages/Home.jsx": "import React from 'react';\nimport { useHabits } from '../context/HabitContext.jsx';\nimport HabitItem from '../components/HabitItem.jsx';\n\nexport default function Home() {\n  const { habits } = useHabits();\n\n  const total = habits.length;\n  const completedToday = habits.filter((h) => {\n    if (!h.completed) return false;\n    const last = new Date(h.lastToggled);\n    const now = new Date();\n    return (\n      last.getDate() === now.getDate() &&\n      last.getMonth() === now.getMonth() &&\n      last.getFullYear() === now.getFullYear()\n    );\n  }).length;\n\n  return (\n    <section>\n      <h1>Ember Habits</h1>\n      <p>\n        You have <strong>{total}</strong> habit{total !== 1 ? 's' : ''} tracked.\n      </p>\n      <p>\n        Today's streak: <strong>{completedToday}</strong> habit\n        {completedToday !== 1 ? 's' : ''} completed.\n      </p>\n\n      {total > 0 && (\n        <ul className=\"habit-list\">\n          {habits.map((h) => (\n            <HabitItem key={h.id} habit={h} />\n          ))}\n        </ul>\n      )}\n    </section>\n  );\n}",
  "src/routes.jsx": "import React from 'react';\nimport { Routes, Route } from 'react-router-dom';\nimport Home from './pages/Home.jsx';\nimport Habits from './pages/Habits.jsx';\n\nexport default function AppRoutes() {\n  return (\n    <Routes>\n      <Route path=\"/\" element={<Home />} />\n      <Route path=\"/habits\" element={<Habits />} />\n    </Routes>\n  );\n}",
  "src/styles.css": "/* Global reset */\n*,\n*::before,\n*::after {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}\n\n/* Warm ember palette */\n:root {\n  --bg-dark: #2b1b0e;\n  --accent: #ff6f3c;\n  --soft: #ff9a56;\n  --light: #ffb86c;\n  --text: #f5e8df;\n}\n\n/* Base styles */\nhtml,\nbody,\n#root {\n  height: 100%;\n  font-family: system-ui, sans-serif;\n  background: var(--bg-dark);\n  color: var(--text);\n  line-height: 1.5;\n}\n\n/* Layout */\n.app {\n  display: flex;\n  flex-direction: column;\n  height: 100%;\n}\n\n.content {\n  flex: 1;\n  overflow-y: auto;\n  padding: 1rem;\n}\n\n/* Nav */\nnav {\n  background: var(--accent);\n  padding: 0.5rem 1rem;\n  display: flex;\n  gap: 1rem;\n}\n\nnav a {\n  color: var(--text);\n  text-decoration: none;\n  font-weight: 600;\n}\n\nnav a.active {\n  border-bottom: 2px solid var(--light);\n}\n\n/* Buttons & inputs */\nbutton,\ninput[type='text'] {\n  font: inherit;\n  padding: 0.5rem;\n  border: none;\n  border-radius: 4px;\n}\n\nbutton {\n  background: var(--soft);\n  color: var(--bg-dark);\n  cursor: pointer;\n}\n\nbutton:hover {\n  background: var(--light);\n}\n\n/* Habit list */\n.habit-list {\n  list-style: none;\n  margin-top: 1rem;\n}\n\n.habit-item {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  background: rgba(255, 111, 60, 0.1);\n  padding: 0.5rem 1rem;\n  margin-bottom: 0.5rem;\n  border-radius: 4px;\n}\n\n.habit-item.completed {\n  text-decoration: line-through;\n  opacity: 0.7;\n}\n\n/* Responsive */\n@media (min-width: 600px) {\n  .content {\n    max-width: 600px;\n    margin: 0 auto;\n  }\n}",
  "vite.config.js": "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});"
};

export const EMBER_HABITS_PROJECT_FILES: ProjectFile[] = Object.entries(RAW)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([path, content]) => ({
    path,
    name: path.split('/').pop() || path,
    content,
    icon: iconForProjectPath(path),
  }));
