import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { audio_url, meeting_title, meeting_description } = await req.json();

    if (!audio_url) {
      return Response.json({ error: 'Audio URL required' }, { status: 400 });
    }

    // Step 1: Transcribe the audio
    const transcriptionResult = await base44.integrations.Core.InvokeLLM({
      prompt: `Transcribe the following meeting audio and provide a detailed transcript of the discussion. Format it as a continuous text with speaker labels if possible (e.g., "Speaker 1:", "Speaker 2:", etc.).`,
      file_urls: [audio_url],
      add_context_from_internet: false
    });

    const transcript = transcriptionResult;

    // Step 2: Extract key discussion points and generate structured notes
    const analysisResult = await base44.integrations.Core.InvokeLLM({
      prompt: `You are analyzing a meeting transcript. The meeting was titled: "${meeting_title}"${meeting_description ? `, with agenda: "${meeting_description}"` : ''}.

Here is the transcript:
${transcript}

Please extract and structure the following information:
1. Key discussion points (main topics discussed)
2. Important decisions made
3. Action items with responsible parties (if mentioned)
4. Follow-up points or unresolved issues
5. A brief executive summary of the meeting

Provide comprehensive details but be concise and actionable.`,
      response_json_schema: {
        type: "object",
        properties: {
          executive_summary: {
            type: "string",
            description: "Brief overview of the meeting"
          },
          discussion_points: {
            type: "array",
            items: {
              type: "object",
              properties: {
                topic: { type: "string" },
                details: { type: "string" }
              }
            }
          },
          decisions: {
            type: "array",
            items: {
              type: "object",
              properties: {
                decision: { type: "string" },
                rationale: { type: "string" }
              }
            }
          },
          action_items: {
            type: "array",
            items: {
              type: "object",
              properties: {
                task: { type: "string" },
                assignee: { type: "string" },
                deadline: { type: "string" }
              }
            }
          },
          follow_ups: {
            type: "array",
            items: { type: "string" }
          }
        }
      }
    });

    // Step 3: Generate initial draft notes in a user-friendly format
    const draftNotes = `# Meeting Summary

## Executive Summary
${analysisResult.executive_summary}

## Discussion Points
${analysisResult.discussion_points?.map((point, i) => 
  `### ${i + 1}. ${point.topic}\n${point.details}`
).join('\n\n') || 'No discussion points extracted.'}

## Decisions Made
${analysisResult.decisions?.map((decision, i) => 
  `${i + 1}. **${decision.decision}**\n   - Rationale: ${decision.rationale}`
).join('\n\n') || 'No decisions recorded.'}

## Action Items
${analysisResult.action_items?.map((item, i) => 
  `${i + 1}. ${item.task}\n   - Assigned to: ${item.assignee || 'Unassigned'}\n   - Deadline: ${item.deadline || 'Not specified'}`
).join('\n\n') || 'No action items identified.'}

## Follow-up Points
${analysisResult.follow_ups?.map((point, i) => 
  `${i + 1}. ${point}`
).join('\n') || 'No follow-up points.'}

---
*Generated by AI - Please review and refine as needed*`;

    return Response.json({
      success: true,
      transcript,
      analysis: analysisResult,
      draft_notes: draftNotes
    });

  } catch (error) {
    return Response.json({ 
      error: error.message,
      details: 'Failed to transcribe and analyze meeting audio'
    }, { status: 500 });
  }
});