// Quran metadata: 114 surahs with verse counts and names
export const SURAHS = [
  { number: 1, name: "Al-Fatihah", english: "The Opening", verses: 7, juz: 1 },
  { number: 2, name: "Al-Baqarah", english: "The Cow", verses: 286, juz: 1 },
  { number: 3, name: "Ali 'Imran", english: "Family of Imran", verses: 200, juz: 3 },
  { number: 4, name: "An-Nisa", english: "The Women", verses: 176, juz: 4 },
  { number: 5, name: "Al-Ma'idah", english: "The Table Spread", verses: 120, juz: 6 },
  { number: 6, name: "Al-An'am", english: "The Cattle", verses: 165, juz: 7 },
  { number: 7, name: "Al-A'raf", english: "The Heights", verses: 206, juz: 8 },
  { number: 8, name: "Al-Anfal", english: "The Spoils of War", verses: 75, juz: 9 },
  { number: 9, name: "At-Tawbah", english: "The Repentance", verses: 129, juz: 10 },
  { number: 10, name: "Yunus", english: "Jonah", verses: 109, juz: 11 },
  { number: 11, name: "Hud", english: "Hud", verses: 123, juz: 11 },
  { number: 12, name: "Yusuf", english: "Joseph", verses: 111, juz: 12 },
  { number: 13, name: "Ar-Ra'd", english: "The Thunder", verses: 43, juz: 13 },
  { number: 14, name: "Ibrahim", english: "Abraham", verses: 52, juz: 13 },
  { number: 15, name: "Al-Hijr", english: "The Rocky Tract", verses: 99, juz: 14 },
  { number: 16, name: "An-Nahl", english: "The Bee", verses: 128, juz: 14 },
  { number: 17, name: "Al-Isra", english: "The Night Journey", verses: 111, juz: 15 },
  { number: 18, name: "Al-Kahf", english: "The Cave", verses: 110, juz: 15 },
  { number: 19, name: "Maryam", english: "Mary", verses: 98, juz: 16 },
  { number: 20, name: "Ta-Ha", english: "Ta-Ha", verses: 135, juz: 16 },
  { number: 21, name: "Al-Anbiya", english: "The Prophets", verses: 112, juz: 17 },
  { number: 22, name: "Al-Hajj", english: "The Pilgrimage", verses: 78, juz: 17 },
  { number: 23, name: "Al-Mu'minun", english: "The Believers", verses: 118, juz: 18 },
  { number: 24, name: "An-Nur", english: "The Light", verses: 64, juz: 18 },
  { number: 25, name: "Al-Furqan", english: "The Criterion", verses: 77, juz: 18 },
  { number: 26, name: "Ash-Shu'ara", english: "The Poets", verses: 227, juz: 19 },
  { number: 27, name: "An-Naml", english: "The Ant", verses: 93, juz: 19 },
  { number: 28, name: "Al-Qasas", english: "The Stories", verses: 88, juz: 20 },
  { number: 29, name: "Al-Ankabut", english: "The Spider", verses: 69, juz: 20 },
  { number: 30, name: "Ar-Rum", english: "The Romans", verses: 60, juz: 21 },
  { number: 31, name: "Luqman", english: "Luqman", verses: 34, juz: 21 },
  { number: 32, name: "As-Sajdah", english: "The Prostration", verses: 30, juz: 21 },
  { number: 33, name: "Al-Ahzab", english: "The Combined Forces", verses: 73, juz: 21 },
  { number: 34, name: "Saba", english: "Sheba", verses: 54, juz: 22 },
  { number: 35, name: "Fatir", english: "Originator", verses: 45, juz: 22 },
  { number: 36, name: "Ya-Sin", english: "Ya Sin", verses: 83, juz: 22 },
  { number: 37, name: "As-Saffat", english: "Those who set the Ranks", verses: 182, juz: 23 },
  { number: 38, name: "Sad", english: "The Letter Sad", verses: 88, juz: 23 },
  { number: 39, name: "Az-Zumar", english: "The Troops", verses: 75, juz: 23 },
  { number: 40, name: "Ghafir", english: "The Forgiver", verses: 85, juz: 24 },
  { number: 41, name: "Fussilat", english: "Explained in Detail", verses: 54, juz: 24 },
  { number: 42, name: "Ash-Shuraa", english: "The Consultation", verses: 53, juz: 25 },
  { number: 43, name: "Az-Zukhruf", english: "The Ornaments of Gold", verses: 89, juz: 25 },
  { number: 44, name: "Ad-Dukhan", english: "The Smoke", verses: 59, juz: 25 },
  { number: 45, name: "Al-Jathiyah", english: "The Crouching", verses: 37, juz: 25 },
  { number: 46, name: "Al-Ahqaf", english: "The Wind-Curved Sandhills", verses: 35, juz: 26 },
  { number: 47, name: "Muhammad", english: "Muhammad", verses: 38, juz: 26 },
  { number: 48, name: "Al-Fath", english: "The Victory", verses: 29, juz: 26 },
  { number: 49, name: "Al-Hujurat", english: "The Rooms", verses: 18, juz: 26 },
  { number: 50, name: "Qaf", english: "The Letter Qaf", verses: 45, juz: 26 },
  { number: 51, name: "Adh-Dhariyat", english: "The Winnowing Winds", verses: 60, juz: 26 },
  { number: 52, name: "At-Tur", english: "The Mount", verses: 49, juz: 27 },
  { number: 53, name: "An-Najm", english: "The Star", verses: 62, juz: 27 },
  { number: 54, name: "Al-Qamar", english: "The Moon", verses: 55, juz: 27 },
  { number: 55, name: "Ar-Rahman", english: "The Beneficent", verses: 78, juz: 27 },
  { number: 56, name: "Al-Waqi'ah", english: "The Inevitable", verses: 96, juz: 27 },
  { number: 57, name: "Al-Hadid", english: "The Iron", verses: 29, juz: 27 },
  { number: 58, name: "Al-Mujadila", english: "The Pleading Woman", verses: 22, juz: 28 },
  { number: 59, name: "Al-Hashr", english: "The Exile", verses: 24, juz: 28 },
  { number: 60, name: "Al-Mumtahanah", english: "She that is to be examined", verses: 13, juz: 28 },
  { number: 61, name: "As-Saf", english: "The Ranks", verses: 14, juz: 28 },
  { number: 62, name: "Al-Jumu'ah", english: "The Congregation", verses: 11, juz: 28 },
  { number: 63, name: "Al-Munafiqun", english: "The Hypocrites", verses: 11, juz: 28 },
  { number: 64, name: "At-Taghabun", english: "The Mutual Disillusion", verses: 18, juz: 28 },
  { number: 65, name: "At-Talaq", english: "The Divorce", verses: 12, juz: 28 },
  { number: 66, name: "At-Tahrim", english: "The Prohibition", verses: 12, juz: 28 },
  { number: 67, name: "Al-Mulk", english: "The Sovereignty", verses: 30, juz: 29 },
  { number: 68, name: "Al-Qalam", english: "The Pen", verses: 52, juz: 29 },
  { number: 69, name: "Al-Haqqah", english: "The Reality", verses: 52, juz: 29 },
  { number: 70, name: "Al-Ma'arij", english: "The Ascending Stairways", verses: 44, juz: 29 },
  { number: 71, name: "Nuh", english: "Noah", verses: 28, juz: 29 },
  { number: 72, name: "Al-Jinn", english: "The Jinn", verses: 28, juz: 29 },
  { number: 73, name: "Al-Muzzammil", english: "The Enshrouded One", verses: 20, juz: 29 },
  { number: 74, name: "Al-Muddaththir", english: "The Cloaked One", verses: 56, juz: 29 },
  { number: 75, name: "Al-Qiyamah", english: "The Resurrection", verses: 40, juz: 29 },
  { number: 76, name: "Al-Insan", english: "The Man", verses: 31, juz: 29 },
  { number: 77, name: "Al-Mursalat", english: "The Emissaries", verses: 50, juz: 29 },
  { number: 78, name: "An-Naba", english: "The Tidings", verses: 40, juz: 30 },
  { number: 79, name: "An-Nazi'at", english: "Those who drag forth", verses: 46, juz: 30 },
  { number: 80, name: "Abasa", english: "He Frowned", verses: 42, juz: 30 },
  { number: 81, name: "At-Takwir", english: "The Overthrowing", verses: 29, juz: 30 },
  { number: 82, name: "Al-Infitar", english: "The Cleaving", verses: 19, juz: 30 },
  { number: 83, name: "Al-Mutaffifin", english: "The Defrauding", verses: 36, juz: 30 },
  { number: 84, name: "Al-Inshiqaq", english: "The Sundering", verses: 25, juz: 30 },
  { number: 85, name: "Al-Buruj", english: "The Mansions of the Stars", verses: 22, juz: 30 },
  { number: 86, name: "At-Tariq", english: "The Morning Star", verses: 17, juz: 30 },
  { number: 87, name: "Al-A'la", english: "The Most High", verses: 19, juz: 30 },
  { number: 88, name: "Al-Ghashiyah", english: "The Overwhelming", verses: 26, juz: 30 },
  { number: 89, name: "Al-Fajr", english: "The Dawn", verses: 30, juz: 30 },
  { number: 90, name: "Al-Balad", english: "The City", verses: 20, juz: 30 },
  { number: 91, name: "Ash-Shams", english: "The Sun", verses: 15, juz: 30 },
  { number: 92, name: "Al-Layl", english: "The Night", verses: 21, juz: 30 },
  { number: 93, name: "Ad-Duha", english: "The Morning Hours", verses: 11, juz: 30 },
  { number: 94, name: "Ash-Sharh", english: "The Relief", verses: 8, juz: 30 },
  { number: 95, name: "At-Tin", english: "The Fig", verses: 8, juz: 30 },
  { number: 96, name: "Al-Alaq", english: "The Clot", verses: 19, juz: 30 },
  { number: 97, name: "Al-Qadr", english: "The Power", verses: 5, juz: 30 },
  { number: 98, name: "Al-Bayyinah", english: "The Clear Proof", verses: 8, juz: 30 },
  { number: 99, name: "Az-Zalzalah", english: "The Earthquake", verses: 8, juz: 30 },
  { number: 100, name: "Al-Adiyat", english: "The Courser", verses: 11, juz: 30 },
  { number: 101, name: "Al-Qari'ah", english: "The Calamity", verses: 11, juz: 30 },
  { number: 102, name: "At-Takathur", english: "The Rivalry in World Increase", verses: 8, juz: 30 },
  { number: 103, name: "Al-Asr", english: "The Declining Day", verses: 3, juz: 30 },
  { number: 104, name: "Al-Humazah", english: "The Traducer", verses: 9, juz: 30 },
  { number: 105, name: "Al-Fil", english: "The Elephant", verses: 5, juz: 30 },
  { number: 106, name: "Quraysh", english: "Quraysh", verses: 4, juz: 30 },
  { number: 107, name: "Al-Ma'un", english: "The Small Kindnesses", verses: 7, juz: 30 },
  { number: 108, name: "Al-Kawthar", english: "The Abundance", verses: 3, juz: 30 },
  { number: 109, name: "Al-Kafirun", english: "The Disbelievers", verses: 6, juz: 30 },
  { number: 110, name: "An-Nasr", english: "The Divine Support", verses: 3, juz: 30 },
  { number: 111, name: "Al-Masad", english: "The Palm Fiber", verses: 5, juz: 30 },
  { number: 112, name: "Al-Ikhlas", english: "The Sincerity", verses: 4, juz: 30 },
  { number: 113, name: "Al-Falaq", english: "The Daybreak", verses: 5, juz: 30 },
  { number: 114, name: "An-Nas", english: "Mankind", verses: 6, juz: 30 }
];

export const TOTAL_VERSES = SURAHS.reduce((sum, s) => sum + s.verses, 0); // 6236
export const TOTAL_PAGES = 604;

// Curated Hadith database
export const HADITH_DB = [
  {
    id: 1,
    arabic: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ",
    english: "Actions are judged by intentions. Every person will get the reward according to what he has intended.",
    narrator: "Umar ibn al-Khattab (RA)",
    source: "Sahih Bukhari",
    reference: "Book 1, Hadith 1",
    category: "faith"
  },
  {
    id: 2,
    arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    english: "A Muslim is the one from whose tongue and hands the Muslims are safe.",
    narrator: "Abu Hurairah (RA)",
    source: "Sahih Bukhari",
    reference: "Book 2, Hadith 9",
    category: "character"
  },
  {
    id: 3,
    arabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ",
    english: "Seeking knowledge is an obligation upon every Muslim.",
    narrator: "Anas ibn Malik (RA)",
    source: "Sunan Ibn Majah",
    reference: "Book 1, Hadith 224",
    category: "knowledge"
  },
  {
    id: 4,
    arabic: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    english: "None of you truly believes until he loves for his brother what he loves for himself.",
    narrator: "Anas ibn Malik (RA)",
    source: "Sahih Bukhari",
    reference: "Book 2, Hadith 13",
    category: "faith"
  },
  {
    id: 5,
    arabic: "الصَّلَوَاتُ الْخَمْسُ وَالْجُمُعَةُ إِلَى الْجُمُعَةِ كَفَّارَةٌ لِمَا بَيْنَهُنَّ",
    english: "The five daily prayers and Friday to Friday are expiation for what is between them, as long as major sins are avoided.",
    narrator: "Abu Hurairah (RA)",
    source: "Sahih Muslim",
    reference: "Book 2, Hadith 233",
    category: "prayer"
  },
  {
    id: 6,
    arabic: "أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    english: "The most beloved deeds to Allah are those done consistently, even if they are small.",
    narrator: "Aisha (RA)",
    source: "Sahih Bukhari",
    reference: "Book 76, Hadith 471",
    category: "general"
  },
  {
    id: 7,
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    english: "Whoever believes in Allah and the Last Day should speak good or remain silent.",
    narrator: "Abu Hurairah (RA)",
    source: "Sahih Bukhari",
    reference: "Book 78, Hadith 158",
    category: "character"
  },
  {
    id: 8,
    arabic: "الدِّينُ النَّصِيحَةُ",
    english: "The religion is sincere advice/good counsel.",
    narrator: "Tamim al-Dari (RA)",
    source: "Sahih Muslim",
    reference: "Book 1, Hadith 95",
    category: "faith"
  },
  {
    id: 9,
    arabic: "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلًا أَنْ يُتْقِنَهُ",
    english: "Indeed, Allah loves that when one of you does a deed, he does it with excellence.",
    narrator: "Aisha (RA)",
    source: "Shu'ab al-Iman",
    reference: "Hadith 5312",
    category: "general"
  },
  {
    id: 10,
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    english: "The best of you are those who learn the Quran and teach it.",
    narrator: "Uthman ibn Affan (RA)",
    source: "Sahih Bukhari",
    reference: "Book 61, Hadith 545",
    category: "knowledge"
  },
  {
    id: 11,
    arabic: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا",
    english: "The believers are like one structure, each part supporting the other.",
    narrator: "Abu Musa al-Ash'ari (RA)",
    source: "Sahih Bukhari",
    reference: "Book 73, Hadith 85",
    category: "general"
  },
  {
    id: 12,
    arabic: "مَنْ أَحَبَّ لِقَاءَ اللَّهِ أَحَبَّ اللَّهُ لِقَاءَهُ",
    english: "Whoever loves to meet Allah, Allah loves to meet him.",
    narrator: "Ubadah ibn as-Samit (RA)",
    source: "Sahih Bukhari",
    reference: "Book 81, Hadith 3",
    category: "faith"
  },
  {
    id: 13,
    arabic: "الصَّوْمُ جُنَّةٌ",
    english: "Fasting is a shield (from sins and from the Hellfire).",
    narrator: "Abu Hurairah (RA)",
    source: "Sahih Bukhari",
    reference: "Book 30, Hadith 2",
    category: "fasting"
  },
  {
    id: 14,
    arabic: "بِرَّ أُمَّكَ ثُمَّ أُمَّكَ ثُمَّ أُمَّكَ ثُمَّ أَبَاكَ",
    english: "Be dutiful to your mother, then your mother, then your mother, then your father.",
    narrator: "Abu Hurairah (RA)",
    source: "Sahih Bukhari",
    reference: "Book 78, Hadith 2",
    category: "family"
  },
  {
    id: 15,
    arabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ لَا يَظْلِمُهُ وَلَا يُسْلِمُهُ",
    english: "A Muslim is the brother of a Muslim. He should not oppress him nor hand him over to the oppressor.",
    narrator: "Abdullah ibn Umar (RA)",
    source: "Sahih Bukhari",
    reference: "Book 46, Hadith 736",
    category: "character"
  }
];