import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Navbar
    services: "Services",
    about: "About",
    pricing: "Pricing",
    blog: "Blog",
    results: "Results",
    myAccount: "My Account",
    getToKnowYou: "Get to Know You",
    signIn: "Sign In",
    signOut: "Sign Out",
    dashboard: "Dashboard",
    clientPortal: "Client Portal",
    aiCoach: "AI Coach",
    leadershipGoals: "Leadership Goals",
    performanceInsights: "Performance Insights",
    mySessions: "My Sessions",
    resources: "Resources",
    // Hero
    heroTag: "International Executive Coaching",
    heroTitle1: "Navigate your",
    heroTitle2: "path to",
    heroTitle3: "extraordinary",
    heroDesc: "Led by Nishat Ismail-Kemih and an elite team of international, multi-lingual coaches. We transform how leaders communicate, influence and impact across cultures and global stages.",
    getToKnowYouBtn: "Get to Know You",
    freeDiscovery: "Free Discovery Call",
    bookSession: "Book a Session",
    startFreeCall: "Start with a Free Call",
    countriesServed: "Countries Served",
    executivesCoached: "Executives Coached",
    languagesCultures: "Languages & Cultures",
    // About
    aboutNishat: "About Nishat",
    founderTitle: "Founder & Lead Consultant",
    aboutBio: "Nishat Ismail-Kemih is a UK-based communication and media consultant and English Coach with 20 years of international experience. Nishat has worked across media, government, finance and automotive sectors — coaching executives, directing corporate films and advising on communication strategies globally.",
    aboutBio2: "Her team coaches in four languages — English, French, Arabic and Urdu — making North South Consulting uniquely positioned to serve international executives and organisations operating across cultural boundaries.",
    aboutBio3: "Nishat has worked on projects for Canon, Stellantis, Kellogg's, Al Jazeera, BBC, National Geographic, HSBC, ITV, Channel 4, Channel 5, Qatar Media Corporation, Gulf Drilling International, and numerous government and diplomatic organisations.",
    credentialYears: "20+ years of experience",
    credentialBased: "UK & France based",
    credentialMultilingual: "International & multilingual",
    credentialGovernment: "Government advisory work",
    credentialFilm: "Corporate film director",
    credentialMA: "MA Communication — Coventry University",
    skillsTitle: "What Nishat brings to every engagement",
    skillsTag: "Skills & Expertise",
    clientsTag: "Clients & Organisations",
    clientsTitle: "A global roster across major sectors",
    sectorsLabel: "Sectors",
    // What we do
    whatWeDoTag: "What We Can Do For You",
    whatWeDoTitle: "Your transformation.",
    whatWeDoSubtitle: "Our commitment.",
    whatWeDoDesc: "With 20 years of international experience, Nishat and her team are committed to one outcome — your growth. Every engagement is bespoke, confidential and built around your goals.",
    // Services
    whatWeOffer: "What We Offer",
    servicesTitle: "Comprehensive coaching",
    servicesSubtitle: "for every dimension of leadership",
    readyToBegin: "Ready to begin?",
    servicesCtaTitle: "Every transformation starts with a conversation.",
    servicesCtaDesc: "Book a free 30-minute discovery call. No commitment — just clarity.",
    // Pricing
    monthlyBilling: "Monthly",
    annualBilling: "Annual",
    savePercent: "Save 20%",
    // Footer
    getInTouch: "Get In Touch",
    footerTagline: "Every transformation starts with a conversation.",
    footerDesc: "Whether you're elevating your communication, preparing for media, or developing executive presence — reach out and we'll respond within 24–48 hours.",
    footerQuote: "\"Raise your words not your voice. It is rain that grows flowers, not thunder.\" — Rumi",
    footerServicesLabel: "Services",
    footerPlatformLabel: "Platform",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    // Floating assistant
    assistantGreeting: "Hello! I'm the NSC Assistant. Ask me about services, pricing, or how to get started.",
    assistantPlaceholder: "Ask me anything...",
    // AI Coach
    uploadAudio: "Upload Audio/Video",
    uploadDesc: "Upload a recording of your practice session for AI analysis",
    analyseFile: "Analyse Recording",
    analyseSpeech: "Analyse Speech",
    analysing: "Analysing...",
    orPasteTranscript: "Or paste a transcript",
    // CTA
    ctaTitle: "Turn insight into action.",
    ctaDesc: "Book a free discovery call and take the first step towards extraordinary communication.",
    freeDiscoveryCall: "Free Discovery Call",
    clientSatisfaction: "client satisfaction",
    insights: "Insights",
    insightsTag: "Insights & Results",
    insightsTitle: "Knowledge. Proof.",
    insightsSubtitle: "Transformation.",
    insightsDesc: "Practical insights from 20 years of coaching, and real results from real engagements.",
    tabAll: "All",
    tabArticles: "Articles",
    tabCaseStudies: "Case Studies",
    articlesTitle: "Articles & Insights",
    caseStudiesTitle: "Client Transformations",
    featuredLabel: "Featured",
    readArticle: "Read article",
    readMore: "Read more",
    insightsCtaSub: "Your transformation starts here.",
    assistantSuggestions: ["💰 Pricing", "📅 Book a call", "🌍 Services", "👤 About Nishat"],
  },
  fr: {
    services: "Services",
    about: "À propos",
    pricing: "Tarifs",
    blog: "Blog",
    results: "Résultats",
    myAccount: "Mon Compte",
    getToKnowYou: "Faisons Connaissance",
    signIn: "Connexion",
    signOut: "Déconnexion",
    dashboard: "Tableau de bord",
    clientPortal: "Portail Client",
    aiCoach: "Coach IA",
    leadershipGoals: "Objectifs Leadership",
    performanceInsights: "Analyses de Performance",
    mySessions: "Mes Sessions",
    resources: "Ressources",
    heroTag: "Coaching Exécutif International",
    heroTitle1: "Naviguez votre",
    heroTitle2: "chemin vers",
    heroTitle3: "l'extraordinaire",
    heroDesc: "Dirigé par Nishat Ismail-Kemih et une équipe de coachs internationaux multilingues. Nous transformons la façon dont les leaders communiquent et impactent à travers les cultures.",
    getToKnowYouBtn: "Faisons Connaissance",
    freeDiscovery: "Appel Découverte Gratuit",
    bookSession: "Réserver une Session",
    startFreeCall: "Commencer par un Appel Gratuit",
    countriesServed: "Pays Desservis",
    executivesCoached: "Dirigeants Coachés",
    languagesCultures: "Langues & Cultures",
    aboutNishat: "À propos de Nishat",
    founderTitle: "Fondatrice & Consultante Principale",
    aboutBio: "Consultante en Communication & Médias et Coach en Anglais avec 20 ans d'expérience internationale. Nishat a travaillé dans les médias, le gouvernement, la finance et l'automobile — coachant des dirigeants et conseillant des stratégies de communication mondiales.",
    aboutBio2: "Elle a négocié avec des personnalités politiques mondiales et croit en une approche professionnelle et personnelle — toujours confidentielle, toujours axée sur les résultats.",
    credentialYears: "20 ans d'expérience",
    credentialBased: "Basée au Royaume-Uni & en France",
    credentialMultilingual: "Internationale & multilingue",
    credentialGovernment: "Conseil gouvernemental",
    credentialFilm: "Réalisatrice de films d'entreprise",
    credentialMA: "MA Communication — Université de Coventry",
    skillsTitle: "Ce que Nishat apporte à chaque engagement",
    skillsTag: "Compétences & Expertise",
    clientsTag: "Clients & Organisations",
    clientsTitle: "Un portefeuille mondial dans les secteurs majeurs",
    sectorsLabel: "Secteurs",
    whatWeDoTag: "Ce Que Nous Pouvons Faire Pour Vous",
    whatWeDoTitle: "Votre transformation.",
    whatWeDoSubtitle: "Notre engagement.",
    whatWeDoDesc: "Avec 20 ans d'expérience internationale, Nishat et son équipe sont engagées vers un seul résultat — votre croissance. Chaque engagement est sur mesure, confidentiel et construit autour de vos objectifs.",
    whatWeOffer: "Ce Que Nous Offrons",
    servicesTitle: "Coaching complet",
    servicesSubtitle: "pour chaque dimension du leadership",
    readyToBegin: "Prêt à commencer ?",
    servicesCtaTitle: "Chaque transformation commence par une conversation.",
    servicesCtaDesc: "Réservez un appel découverte gratuit de 30 minutes. Sans engagement — juste de la clarté.",
    monthlyBilling: "Mensuel",
    annualBilling: "Annuel",
    savePercent: "Économisez 20%",
    getInTouch: "Contactez-Nous",
    footerTagline: "Chaque transformation commence par une conversation.",
    footerDesc: "Que vous souhaitiez améliorer votre communication, vous préparer aux médias ou développer votre présence exécutive — contactez-nous et nous répondrons sous 24–48 heures.",
    footerQuote: "\"Élevez vos mots, pas votre voix. C'est la pluie qui fait pousser les fleurs, pas le tonnerre.\" — Rumi",
    footerServicesLabel: "Services",
    footerPlatformLabel: "Plateforme",
    privacyPolicy: "Politique de Confidentialité",
    termsOfService: "Conditions d'Utilisation",
    assistantGreeting: "Bonjour ! Je suis l'assistante NSC. Posez-moi des questions sur nos services, tarifs ou comment commencer.",
    assistantPlaceholder: "Posez votre question...",
    uploadAudio: "Télécharger Audio/Vidéo",
    uploadDesc: "Téléchargez un enregistrement de votre session pour une analyse IA",
    analyseFile: "Analyser l'Enregistrement",
    analyseSpeech: "Analyser le Discours",
    analysing: "Analyse en cours...",
    orPasteTranscript: "Ou coller une transcription",
    ctaTitle: "Transformez l'insight en action.",
    ctaDesc: "Réservez un appel découverte gratuit et faites le premier pas vers une communication extraordinaire.",
    freeDiscoveryCall: "Appel Découverte Gratuit",
    clientSatisfaction: "satisfaction client",
    insights: "Analyses",
    insightsTag: "Analyses & Résultats",
    insightsTitle: "Savoir. Preuve.",
    insightsSubtitle: "Transformation.",
    insightsDesc: "Des analyses pratiques tirées de 20 ans de coaching, et des résultats réels d'engagements réels.",
    tabAll: "Tout",
    tabArticles: "Articles",
    tabCaseStudies: "Études de cas",
    articlesTitle: "Articles & Analyses",
    caseStudiesTitle: "Transformations Clients",
    featuredLabel: "À la une",
    readArticle: "Lire l'article",
    readMore: "Lire la suite",
    insightsCtaSub: "Votre transformation commence ici.",
    assistantSuggestions: ["💰 Tarifs", "📅 Réserver", "🌍 Services", "👤 Nishat"],
  },
  ar: {
    services: "الخدمات",
    about: "عن نيشات",
    pricing: "الأسعار",
    blog: "المدونة",
    results: "النتائج",
    myAccount: "حسابي",
    getToKnowYou: "تعرف علينا",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    dashboard: "لوحة التحكم",
    clientPortal: "بوابة العميل",
    aiCoach: "مدرب الذكاء الاصطناعي",
    leadershipGoals: "أهداف القيادة",
    performanceInsights: "تحليلات الأداء",
    mySessions: "جلساتي",
    resources: "الموارد",
    heroTag: "تدريب تنفيذي دولي",
    heroTitle1: "تنقّل في طريقك",
    heroTitle2: "نحو",
    heroTitle3: "الاستثنائي",
    heroDesc: "بقيادة نيشات إسماعيل-كيميه وفريق من المدربين الدوليين متعددي اللغات. نحن نحوّل طريقة تواصل القادة وتأثيرهم عبر الثقافات والمسارح العالمية.",
    getToKnowYouBtn: "تعرف علينا",
    freeDiscovery: "مكالمة استكشافية مجانية",
    bookSession: "احجز جلسة",
    startFreeCall: "ابدأ بمكالمة مجانية",
    countriesServed: "دولة نخدمها",
    executivesCoached: "مدير تم تدريبه",
    languagesCultures: "لغات وثقافات",
    aboutNishat: "عن نيشات",
    founderTitle: "المؤسسة والمستشارة الرئيسية",
    aboutBio: "مستشارة في الاتصال والإعلام ومدربة لغة إنجليزية بخبرة دولية تمتد 20 عاماً. عملت نيشات في قطاعات الإعلام والحكومة والمال والسيارات — لتدريب المديرين وإخراج الأفلام المؤسسية وتقديم المشورة حول استراتيجيات الاتصال عالمياً.",
    aboutBio2: "تؤمن بأسلوب مهني وشخصي — دائماً سري، دائماً يركز على النتائج.",
    credentialYears: "20 عاماً من الخبرة",
    credentialBased: "مقيمة في المملكة المتحدة وفرنسا",
    credentialMultilingual: "دولية ومتعددة اللغات",
    credentialGovernment: "استشارات حكومية",
    credentialFilm: "مخرجة أفلام مؤسسية",
    credentialMA: "ماجستير اتصال — جامعة كوفنتري",
    skillsTitle: "ما تجلبه نيشات لكل مشاركة",
    skillsTag: "المهارات والخبرة",
    clientsTag: "العملاء والمنظمات",
    clientsTitle: "قائمة عملاء عالمية عبر القطاعات الكبرى",
    sectorsLabel: "القطاعات",
    whatWeDoTag: "ما يمكننا فعله لك",
    whatWeDoTitle: "تحولك.",
    whatWeDoSubtitle: "التزامنا.",
    whatWeDoDesc: "مع 20 عاماً من الخبرة الدولية، تلتزم نيشات وفريقها بنتيجة واحدة — نموك. كل مشاركة مخصصة وسرية ومبنية حول أهدافك.",
    whatWeOffer: "ما نقدمه",
    servicesTitle: "تدريب شامل",
    servicesSubtitle: "لكل أبعاد القيادة",
    readyToBegin: "مستعد للبدء؟",
    servicesCtaTitle: "كل تحول يبدأ بمحادثة.",
    servicesCtaDesc: "احجز مكالمة استكشافية مجانية لمدة 30 دقيقة. بدون التزام — فقط وضوح.",
    monthlyBilling: "شهري",
    annualBilling: "سنوي",
    savePercent: "وفّر 20%",
    getInTouch: "تواصل معنا",
    footerTagline: "كل تحول يبدأ بمحادثة.",
    footerDesc: "سواء كنت تسعى لتطوير اتصالك أو الاستعداد للإعلام أو تطوير حضورك التنفيذي — تواصل معنا وسنرد خلال 24-48 ساعة.",
    footerQuote: "\"ارفع كلماتك لا صوتك. المطر هو ما يُنبت الزهور، لا الرعد.\" — رومي",
    footerServicesLabel: "الخدمات",
    footerPlatformLabel: "المنصة",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الخدمة",
    assistantGreeting: "مرحباً! أنا مساعدة NSC. اسألني عن الخدمات والأسعار أو كيفية البدء.",
    assistantPlaceholder: "اسألني أي شيء...",
    uploadAudio: "رفع صوت/فيديو",
    uploadDesc: "ارفع تسجيلاً لجلسة تدريبك للتحليل بالذكاء الاصطناعي",
    analyseFile: "تحليل التسجيل",
    analyseSpeech: "تحليل الكلام",
    analysing: "جارٍ التحليل...",
    orPasteTranscript: "أو الصق نصاً مكتوباً",
    ctaTitle: "حوّل الرؤية إلى فعل.",
    ctaDesc: "احجز مكالمة استكشافية مجانية وابدأ نحو تواصل استثنائي.",
    freeDiscoveryCall: "مكالمة استكشافية مجانية",
    clientSatisfaction: "رضا العملاء",
    insights: "المعرفة",
    insightsTag: "مقالات ونتائج",
    insightsTitle: "المعرفة. الدليل.",
    insightsSubtitle: "التحول.",
    insightsDesc: "رؤى عملية من 20 عاماً من التدريب، ونتائج حقيقية من مشاركات حقيقية.",
    tabAll: "الكل",
    tabArticles: "مقالات",
    tabCaseStudies: "دراسات الحالة",
    articlesTitle: "مقالات وتحليلات",
    caseStudiesTitle: "تحولات العملاء",
    featuredLabel: "مميز",
    readArticle: "اقرأ المقال",
    readMore: "اقرأ المزيد",
    insightsCtaSub: "تحولك يبدأ هنا.",
    assistantSuggestions: ["💰 الأسعار", "📅 احجز", "🌍 الخدمات", "👤 عن نيشات"],
  },
  ur: {
    services: "خدمات",
    about: "نشاط کے بارے میں",
    pricing: "قیمتیں",
    blog: "بلاگ",
    results: "نتائج",
    myAccount: "میرا اکاؤنٹ",
    getToKnowYou: "ہمیں جانیں",
    signIn: "سائن ان",
    signOut: "سائن آؤٹ",
    dashboard: "ڈیش بورڈ",
    clientPortal: "کلائنٹ پورٹل",
    aiCoach: "اے آئی کوچ",
    leadershipGoals: "قیادت کے اہداف",
    performanceInsights: "کارکردگی کا تجزیہ",
    mySessions: "میری سیشنز",
    resources: "وسائل",
    heroTag: "بین الاقوامی ایگزیکٹو کوچنگ",
    heroTitle1: "اپنا راستہ",
    heroTitle2: "طے کریں",
    heroTitle3: "غیر معمولی",
    heroDesc: "نشاط اسماعیل-کیمیہ اور ایک اشرافیہ بین الاقوامی کثیر لسانی ٹیم کی قیادت میں۔ ہم قائدین کے بات چیت، اثر انداز ہونے اور اثر ڈالنے کے طریقے کو تبدیل کرتے ہیں۔",
    getToKnowYouBtn: "ہمیں جانیں",
    freeDiscovery: "مفت دریافت کال",
    bookSession: "سیشن بک کریں",
    startFreeCall: "مفت کال سے شروع کریں",
    countriesServed: "خدمت کردہ ممالک",
    executivesCoached: "کوچ کردہ ایگزیکٹوز",
    languagesCultures: "زبانیں اور ثقافتیں",
    aboutNishat: "نشاط کے بارے میں",
    founderTitle: "بانی اور مرکزی مشیر",
    aboutBio: "کمیونیکیشن اور میڈیا مشیر اور انگریزی کوچ جن کے پاس 20 سال کا بین الاقوامی تجربہ ہے۔ نشاط نے میڈیا، حکومت، مالیات اور آٹوموٹیو شعبوں میں کام کیا ہے۔",
    aboutBio2: "وہ ایک پیشہ ورانہ لیکن ذاتی انداز پر یقین رکھتی ہیں — ہمیشہ خفیہ، ہمیشہ نتائج پر مرکوز۔",
    credentialYears: "20 سال کا تجربہ",
    credentialBased: "برطانیہ اور فرانس میں مقیم",
    credentialMultilingual: "بین الاقوامی اور کثیر لسانی",
    credentialGovernment: "حکومتی مشاورت",
    credentialFilm: "کارپوریٹ فلم ڈائریکٹر",
    credentialMA: "ایم اے کمیونیکیشن — کوونٹری یونیورسٹی",
    skillsTitle: "نشاط ہر مشغولیت میں کیا لاتی ہیں",
    skillsTag: "مہارتیں اور تخصص",
    clientsTag: "کلائنٹس اور تنظیمیں",
    clientsTitle: "بڑے شعبوں میں عالمی کلائنٹ فہرست",
    sectorsLabel: "شعبے",
    whatWeDoTag: "ہم آپ کے لیے کیا کر سکتے ہیں",
    whatWeDoTitle: "آپ کی تبدیلی۔",
    whatWeDoSubtitle: "ہمارا وعدہ۔",
    whatWeDoDesc: "20 سال کے بین الاقوامی تجربے کے ساتھ، نشاط اور ان کی ٹیم ایک نتیجے کے لیے پرعزم ہے — آپ کی ترقی۔",
    whatWeOffer: "ہم کیا پیش کرتے ہیں",
    servicesTitle: "جامع کوچنگ",
    servicesSubtitle: "قیادت کے ہر پہلو کے لیے",
    readyToBegin: "شروع کرنے کے لیے تیار؟",
    servicesCtaTitle: "ہر تبدیلی ایک گفتگو سے شروع ہوتی ہے۔",
    servicesCtaDesc: "مفت 30 منٹ کی دریافت کال بک کریں۔ کوئی عہد نہیں — صرف وضاحت۔",
    monthlyBilling: "ماہانہ",
    annualBilling: "سالانہ",
    savePercent: "20% بچائیں",
    getInTouch: "رابطہ کریں",
    footerTagline: "ہر تبدیلی ایک گفتگو سے شروع ہوتی ہے۔",
    footerDesc: "چاہے آپ اپنی کمیونیکیشن کو بہتر بنانا چاہتے ہیں یا میڈیا کی تیاری کرنا — ہم سے رابطہ کریں اور ہم 24-48 گھنٹوں میں جواب دیں گے۔",
    footerQuote: "\"اپنے الفاظ بلند کریں، اپنی آواز نہیں۔ بارش پھول اگاتی ہے، گرج نہیں۔\" — رومی",
    footerServicesLabel: "خدمات",
    footerPlatformLabel: "پلیٹ فارم",
    privacyPolicy: "رازداری پالیسی",
    termsOfService: "خدمت کی شرائط",
    assistantGreeting: "السلام علیکم! میں NSC اسسٹنٹ ہوں۔ خدمات، قیمتوں یا شروعات کے بارے میں پوچھیں۔",
    assistantPlaceholder: "کچھ بھی پوچھیں...",
    uploadAudio: "آڈیو/ویڈیو اپلوڈ کریں",
    uploadDesc: "تجزیہ کے لیے اپنی پریکٹس سیشن کی ریکارڈنگ اپلوڈ کریں",
    analyseFile: "ریکارڈنگ تجزیہ کریں",
    analyseSpeech: "تقریر تجزیہ کریں",
    analysing: "تجزیہ ہو رہا ہے...",
    orPasteTranscript: "یا ٹرانسکرپٹ چسپاں کریں",
    ctaTitle: "بصیرت کو عمل میں بدلیں۔",
    ctaDesc: "مفت دریافت کال بک کریں اور غیر معمولی کمیونیکیشن کی طرف پہلا قدم اٹھائیں۔",
    freeDiscoveryCall: "مفت دریافت کال",
    clientSatisfaction: "کلائنٹ اطمینان",
    insights: "بصیرت",
    insightsTag: "مضامین اور نتائج",
    insightsTitle: "علم۔ ثبوت۔",
    insightsSubtitle: "تبدیلی۔",
    insightsDesc: "20 سال کے تجربے کی عملی بصیرت اور حقیقی نتائج۔",
    tabAll: "سب",
    tabArticles: "مضامین",
    tabCaseStudies: "کیس اسٹڈیز",
    articlesTitle: "مضامین اور بصیرت",
    caseStudiesTitle: "کلائنٹ کی تبدیلیاں",
    featuredLabel: "نمایاں",
    readArticle: "مضمون پڑھیں",
    readMore: "مزید پڑھیں",
    insightsCtaSub: "آپ کی تبدیلی یہاں سے شروع ہوتی ہے۔",
    assistantSuggestions: ["💰 قیمتیں", "📅 بک کریں", "🌍 خدمات", "👤 نشاط"],
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const isRTL = lang === "ar" || lang === "ur";
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      <div dir={isRTL ? "rtl" : "ltr"} style={{ fontFamily: isRTL ? "'Noto Nastaliq Urdu', 'Noto Naskh Arabic', sans-serif" : undefined }}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) return { lang: "en", setLang: () => {}, t: (k) => k, isRTL: false };
  return ctx;
}