import fs from 'fs/promises';
import path from 'path';
import { STORAGE_BUCKET_IMPORTED_APPS } from '@/lib/storage/constants';
import type {
  AppSourceLayer,
  DetectedFramework,
  NiskBuildImportManifest,
} from '@/lib/app-import/types';

const ENV_EXAMPLE = `# NiskBuild dependency injection — copy to .env.local for local dev
VITE_SUPABASE_URL=
VITE_SUPABASE_ANON_KEY=
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
`;

const NISKBUILD_ENV_SHIM = `/**
 * NiskBuild tenant bind — reads Supabase from Vite/Next public env.
 * Generated by the external app import pipeline. Do not remove.
 */
export function getNiskBuildSupabaseConfig() {
  const viteUrl = typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_URL;
  const viteKey = typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY;
  const nextUrl = typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_SUPABASE_URL;
  const nextKey = typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  return {
    url: (viteUrl || nextUrl || '').trim(),
    anonKey: (viteKey || nextKey || '').trim(),
  };
}

export const NISKBUILD_PLATFORM_FEATURES = {
  socialPublisher: true,
  previewSwitcher: true,
  appStoreChecklist: true,
  multiTenantRouting: true,
};
`;

function envShimRelativePath(framework: DetectedFramework): string {
  if (framework === 'next') return 'lib/niskbuild-env.js';
  return 'src/lib/niskbuild-env.js';
}

async function writeEnvShim(workspaceRoot: string, framework: DetectedFramework): Promise<string> {
  const rel = envShimRelativePath(framework);
  const abs = path.join(workspaceRoot, rel);
  await fs.mkdir(path.dirname(abs), { recursive: true });
  await fs.writeFile(abs, NISKBUILD_ENV_SHIM, 'utf8');
  return rel;
}

async function stripForeignRoutingHints(workspaceRoot: string, framework: DetectedFramework): Promise<string[]> {
  const notes: string[] = [];
  const viteConfig = path.join(workspaceRoot, 'vite.config.js');
  const viteConfigTs = path.join(workspaceRoot, 'vite.config.ts');

  for (const cfg of [viteConfig, viteConfigTs]) {
    try {
      let content = await fs.readFile(cfg, 'utf8');
      if (content.includes('@base44/vite-plugin')) {
        notes.push('Detected Base44 Vite plugin — migrate to Supabase via niskbuild-env.js');
      }
      if (!content.includes('NISKBUILD_IMPORT')) {
        content = `// NISKBUILD_IMPORT: normalized by NiskBuild ingestion pipeline\n${content}`;
        await fs.writeFile(cfg, content, 'utf8');
        notes.push(`Tagged ${path.basename(cfg)} for NiskBuild normalization`);
      }
    } catch {
      /* optional file */
    }
  }

  if (framework === 'next') {
    notes.push('Next.js app — use App Router under app/ with public Supabase tables');
  }

  return notes;
}

export async function normalizeImportedWorkspace(params: {
  workspaceRoot: string;
  slug: string;
  title: string;
  framework: DetectedFramework;
  sourceLayer: AppSourceLayer;
  entryFiles: string[];
  fileCount: number;
  storagePath: string;
}): Promise<{ manifest: NiskBuildImportManifest; notes: string[] }> {
  const { workspaceRoot, slug, title, framework, sourceLayer, entryFiles, fileCount, storagePath } =
    params;

  await fs.writeFile(path.join(workspaceRoot, '.env.example'), ENV_EXAMPLE, 'utf8');
  const envShimPath = await writeEnvShim(workspaceRoot, framework);
  const routingNotes = await stripForeignRoutingHints(workspaceRoot, framework);

  const manifest: NiskBuildImportManifest = {
    version: '1.0',
    slug,
    title,
    framework,
    storagePath,
    storageBucket: STORAGE_BUCKET_IMPORTED_APPS,
    sourceLayer,
    importedAt: new Date().toISOString(),
    entryFiles,
    features: {
      socialPublisher: true,
      previewSwitcher: true,
      appStoreChecklist: true,
      multiTenantRouting: true,
    },
    envKeys: [
      'VITE_SUPABASE_URL',
      'VITE_SUPABASE_ANON_KEY',
      'NEXT_PUBLIC_SUPABASE_URL',
      'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    ],
  };

  await fs.writeFile(
    path.join(workspaceRoot, 'niskbuild.import.json'),
    `${JSON.stringify({ ...manifest, envShimPath, fileCount }, null, 2)}\n`,
    'utf8'
  );

  const readme = `# ${title}

Imported via NiskBuild External App Ingestion Engine.

- **Slug:** \`${slug}\`
- **Framework:** ${framework}
- **Storage:** \`${STORAGE_BUCKET_IMPORTED_APPS}/${storagePath}\`

## Dependency injection

1. Copy \`.env.example\` → \`.env.local\`
2. Set \`VITE_SUPABASE_URL\` and \`VITE_SUPABASE_ANON_KEY\` (or Next public equivalents)
3. Import \`${envShimPath}\` where you initialize Supabase

## Platform features enabled

Social publisher, preview switcher, App Store checklist, and multi-tenant routing are available through the NiskBuild tenant bind manifest (\`niskbuild.import.json\`).
`;

  await fs.writeFile(path.join(workspaceRoot, 'NISKBUILD_IMPORT.md'), readme, 'utf8');

  return {
    manifest,
    notes: [
      `Normalized ${fileCount} files for storage upload`,
      `Injected ${envShimPath} and .env.example`,
      ...routingNotes,
    ],
  };
}
