// Complete list of all 114 Surahs of the Quran
export const SURAHS = [
  { number: 1, name: "Al-Fatihah", englishName: "The Opening", verses: 7, revelation: "Meccan" },
  { number: 2, name: "Al-Baqarah", englishName: "The Cow", verses: 286, revelation: "Medinan" },
  { number: 3, name: "Ali 'Imran", englishName: "Family of Imran", verses: 200, revelation: "Medinan" },
  { number: 4, name: "An-Nisa", englishName: "The Women", verses: 176, revelation: "Medinan" },
  { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread", verses: 120, revelation: "Medinan" },
  { number: 6, name: "Al-An'am", englishName: "The Cattle", verses: 165, revelation: "Meccan" },
  { number: 7, name: "Al-A'raf", englishName: "The Heights", verses: 206, revelation: "Meccan" },
  { number: 8, name: "Al-Anfal", englishName: "The Spoils of War", verses: 75, revelation: "Medinan" },
  { number: 9, name: "At-Tawbah", englishName: "The Repentance", verses: 129, revelation: "Medinan" },
  { number: 10, name: "Yunus", englishName: "Jonah", verses: 109, revelation: "Meccan" },
  { number: 11, name: "Hud", englishName: "Hud", verses: 123, revelation: "Meccan" },
  { number: 12, name: "Yusuf", englishName: "Joseph", verses: 111, revelation: "Meccan" },
  { number: 13, name: "Ar-Ra'd", englishName: "The Thunder", verses: 43, revelation: "Medinan" },
  { number: 14, name: "Ibrahim", englishName: "Abraham", verses: 52, revelation: "Meccan" },
  { number: 15, name: "Al-Hijr", englishName: "The Rocky Tract", verses: 99, revelation: "Meccan" },
  { number: 16, name: "An-Nahl", englishName: "The Bee", verses: 128, revelation: "Meccan" },
  { number: 17, name: "Al-Isra", englishName: "The Night Journey", verses: 111, revelation: "Meccan" },
  { number: 18, name: "Al-Kahf", englishName: "The Cave", verses: 110, revelation: "Meccan" },
  { number: 19, name: "Maryam", englishName: "Mary", verses: 98, revelation: "Meccan" },
  { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", verses: 135, revelation: "Meccan" },
  { number: 21, name: "Al-Anbya", englishName: "The Prophets", verses: 112, revelation: "Meccan" },
  { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage", verses: 78, revelation: "Medinan" },
  { number: 23, name: "Al-Mu'minun", englishName: "The Believers", verses: 118, revelation: "Meccan" },
  { number: 24, name: "An-Nur", englishName: "The Light", verses: 64, revelation: "Medinan" },
  { number: 25, name: "Al-Furqan", englishName: "The Criterion", verses: 77, revelation: "Meccan" },
  { number: 26, name: "Ash-Shu'ara", englishName: "The Poets", verses: 227, revelation: "Meccan" },
  { number: 27, name: "An-Naml", englishName: "The Ant", verses: 93, revelation: "Meccan" },
  { number: 28, name: "Al-Qasas", englishName: "The Stories", verses: 88, revelation: "Meccan" },
  { number: 29, name: "Al-'Ankabut", englishName: "The Spider", verses: 69, revelation: "Meccan" },
  { number: 30, name: "Ar-Rum", englishName: "The Romans", verses: 60, revelation: "Meccan" },
  { number: 31, name: "Luqman", englishName: "Luqman", verses: 34, revelation: "Meccan" },
  { number: 32, name: "As-Sajdah", englishName: "The Prostration", verses: 30, revelation: "Meccan" },
  { number: 33, name: "Al-Ahzab", englishName: "The Combined Forces", verses: 73, revelation: "Medinan" },
  { number: 34, name: "Saba", englishName: "Sheba", verses: 54, revelation: "Meccan" },
  { number: 35, name: "Fatir", englishName: "Originator", verses: 45, revelation: "Meccan" },
  { number: 36, name: "Ya-Sin", englishName: "Ya-Sin", verses: 83, revelation: "Meccan" },
  { number: 37, name: "As-Saffat", englishName: "Those Ranges in Ranks", verses: 182, revelation: "Meccan" },
  { number: 38, name: "Sad", englishName: "The Letter Sad", verses: 88, revelation: "Meccan" },
  { number: 39, name: "Az-Zumar", englishName: "The Groups", verses: 75, revelation: "Meccan" },
  { number: 40, name: "Ghafir", englishName: "The Forgiver", verses: 85, revelation: "Meccan" },
  { number: 41, name: "Fussilat", englishName: "Explained in Detail", verses: 54, revelation: "Meccan" },
  { number: 42, name: "Ash-Shuraa", englishName: "The Consultation", verses: 53, revelation: "Meccan" },
  { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", verses: 89, revelation: "Meccan" },
  { number: 44, name: "Ad-Dukhan", englishName: "The Smoke", verses: 59, revelation: "Meccan" },
  { number: 45, name: "Al-Jathiyah", englishName: "The Crouching", verses: 37, revelation: "Meccan" },
  { number: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", verses: 35, revelation: "Meccan" },
  { number: 47, name: "Muhammad", englishName: "Muhammad", verses: 38, revelation: "Medinan" },
  { number: 48, name: "Al-Fath", englishName: "The Victory", verses: 29, revelation: "Medinan" },
  { number: 49, name: "Al-Hujurat", englishName: "The Rooms", verses: 18, revelation: "Medinan" },
  { number: 50, name: "Qaf", englishName: "The Letter Qaf", verses: 45, revelation: "Meccan" },
  { number: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds", verses: 60, revelation: "Meccan" },
  { number: 52, name: "At-Tur", englishName: "The Mount", verses: 49, revelation: "Meccan" },
  { number: 53, name: "An-Najm", englishName: "The Star", verses: 62, revelation: "Meccan" },
  { number: 54, name: "Al-Qamar", englishName: "The Moon", verses: 55, revelation: "Meccan" },
  { number: 55, name: "Ar-Rahman", englishName: "The Beneficent", verses: 78, revelation: "Meccan" },
  { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", verses: 96, revelation: "Meccan" },
  { number: 57, name: "Al-Hadid", englishName: "The Iron", verses: 29, revelation: "Medinan" },
  { number: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", verses: 22, revelation: "Medinan" },
  { number: 59, name: "Al-Hashr", englishName: "The Exile", verses: 24, revelation: "Medinan" },
  { number: 60, name: "Al-Mumtahanah", englishName: "She that is to be Examined", verses: 13, revelation: "Medinan" },
  { number: 61, name: "As-Saf", englishName: "The Ranks", verses: 14, revelation: "Medinan" },
  { number: 62, name: "Al-Jumu'ah", englishName: "The Congregation", verses: 11, revelation: "Medinan" },
  { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", verses: 11, revelation: "Medinan" },
  { number: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", verses: 18, revelation: "Medinan" },
  { number: 65, name: "At-Talaq", englishName: "The Divorce", verses: 12, revelation: "Medinan" },
  { number: 66, name: "At-Tahrim", englishName: "The Prohibition", verses: 12, revelation: "Medinan" },
  { number: 67, name: "Al-Mulk", englishName: "The Sovereignty", verses: 30, revelation: "Meccan" },
  { number: 68, name: "Al-Qalam", englishName: "The Pen", verses: 52, revelation: "Meccan" },
  { number: 69, name: "Al-Haqqah", englishName: "The Reality", verses: 52, revelation: "Meccan" },
  { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", verses: 44, revelation: "Meccan" },
  { number: 71, name: "Nuh", englishName: "Noah", verses: 28, revelation: "Meccan" },
  { number: 72, name: "Al-Jinn", englishName: "The Jinn", verses: 28, revelation: "Meccan" },
  { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", verses: 20, revelation: "Meccan" },
  { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", verses: 56, revelation: "Meccan" },
  { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection", verses: 40, revelation: "Meccan" },
  { number: 76, name: "Al-Insan", englishName: "The Man", verses: 31, revelation: "Medinan" },
  { number: 77, name: "Al-Mursalat", englishName: "The Emissaries", verses: 50, revelation: "Meccan" },
  { number: 78, name: "An-Naba", englishName: "The Tidings", verses: 40, revelation: "Meccan" },
  { number: 79, name: "An-Nazi'at", englishName: "Those who Drag Forth", verses: 46, revelation: "Meccan" },
  { number: 80, name: "Abasa", englishName: "He Frowned", verses: 42, revelation: "Meccan" },
  { number: 81, name: "At-Takwir", englishName: "The Overthrowing", verses: 29, revelation: "Meccan" },
  { number: 82, name: "Al-Infitar", englishName: "The Cleaving", verses: 19, revelation: "Meccan" },
  { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", verses: 36, revelation: "Meccan" },
  { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering", verses: 25, revelation: "Meccan" },
  { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", verses: 22, revelation: "Meccan" },
  { number: 86, name: "At-Tariq", englishName: "The Nightcommer", verses: 17, revelation: "Meccan" },
  { number: 87, name: "Al-A'la", englishName: "The Most High", verses: 19, revelation: "Meccan" },
  { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", verses: 26, revelation: "Meccan" },
  { number: 89, name: "Al-Fajr", englishName: "The Dawn", verses: 30, revelation: "Meccan" },
  { number: 90, name: "Al-Balad", englishName: "The City", verses: 20, revelation: "Meccan" },
  { number: 91, name: "Ash-Shams", englishName: "The Sun", verses: 15, revelation: "Meccan" },
  { number: 92, name: "Al-Layl", englishName: "The Night", verses: 21, revelation: "Meccan" },
  { number: 93, name: "Ad-Duhaa", englishName: "The Morning Hours", verses: 11, revelation: "Meccan" },
  { number: 94, name: "Ash-Sharh", englishName: "The Relief", verses: 8, revelation: "Meccan" },
  { number: 95, name: "At-Tin", englishName: "The Fig", verses: 8, revelation: "Meccan" },
  { number: 96, name: "Al-'Alaq", englishName: "The Clot", verses: 19, revelation: "Meccan" },
  { number: 97, name: "Al-Qadr", englishName: "The Power", verses: 5, revelation: "Meccan" },
  { number: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", verses: 8, revelation: "Medinan" },
  { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake", verses: 8, revelation: "Medinan" },
  { number: 100, name: "Al-'Adiyat", englishName: "The Courser", verses: 11, revelation: "Meccan" },
  { number: 101, name: "Al-Qari'ah", englishName: "The Calamity", verses: 11, revelation: "Meccan" },
  { number: 102, name: "At-Takathur", englishName: "The Rivalry in Worldly Increase", verses: 8, revelation: "Meccan" },
  { number: 103, name: "Al-'Asr", englishName: "The Declining Day", verses: 3, revelation: "Meccan" },
  { number: 104, name: "Al-Humazah", englishName: "The Traducer", verses: 9, revelation: "Meccan" },
  { number: 105, name: "Al-Fil", englishName: "The Elephant", verses: 5, revelation: "Meccan" },
  { number: 106, name: "Quraysh", englishName: "Quraysh", verses: 4, revelation: "Meccan" },
  { number: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", verses: 7, revelation: "Meccan" },
  { number: 108, name: "Al-Kawthar", englishName: "The Abundance", verses: 3, revelation: "Meccan" },
  { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers", verses: 6, revelation: "Meccan" },
  { number: 110, name: "An-Nasr", englishName: "The Divine Support", verses: 3, revelation: "Medinan" },
  { number: 111, name: "Al-Masad", englishName: "The Palm Fiber", verses: 5, revelation: "Meccan" },
  { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity", verses: 4, revelation: "Meccan" },
  { number: 113, name: "Al-Falaq", englishName: "The Daybreak", verses: 5, revelation: "Meccan" },
  { number: 114, name: "An-Nas", englishName: "The Mankind", verses: 6, revelation: "Meccan" }
];

export const TRANSLATIONS = [
  { id: 'sahih', name: 'Sahih International', language: 'English' },
  { id: 'yusuf_ali', name: 'Yusuf Ali', language: 'English' },
  { id: 'pickthall', name: 'Pickthall', language: 'English' },
  { id: 'shakir', name: 'Shakir', language: 'English' },
  { id: 'dr_ghali', name: 'Dr. Ghali', language: 'English' }
];

export const RECITERS = [
  { id: 'alafasy', name: 'Mishary Rashid Alafasy', code: 'ar.alafasy' },
  { id: 'minshawi', name: 'Mohamed Siddiq El-Minshawi', code: 'ar.minshawi' },
  { id: 'husary', name: 'Mahmoud Khalil Al-Husary', code: 'ar.husary' },
  { id: 'abdulbasit', name: 'Abdul Basit', code: 'ar.abdulbasit' },
  { id: 'sudais', name: 'Abdurrahman As-Sudais', code: 'ar.abdurrahmaansudais' }
];